# -*- coding: utf-8 -*-
"""GT AI Use-Case Library for the Opportunity Discovery Toolkit.

Every process in the diagnostic is selected from this library, and the recommendation, data needs, KPIs and regulatory
notes shown to the client come from it. Structure:
  - functions follow the APQC Process Classification Framework (cross-industry) level-1 categories;
  - task nature -> solution family follows ISO/IEC 22989 / OECD AI-system classification (see opportunity_data.FAMILIES);
  - minimum risk tier reflects EU AI Act Annex III / Art. 5 categories, sector regulation and Bahrain PDPL;
  - sector entries cover Bahrain priority sectors (BFSI, healthcare, telecom, government, ...).
"""

# function code -> (name, APQC PCF reference)
FUNCTIONS = {
    "STR": ("Strategy, management & reporting", "APQC 1.0 / 13.0"),
    "OPS": ("Core operations & service delivery", "APQC 2.0 / 4.0 / 5.0"),
    "MKT": ("Sales & marketing", "APQC 3.0"),
    "CUS": ("Customer service", "APQC 6.0"),
    "HR": ("HR & people", "APQC 7.0"),
    "IT": ("IT & cybersecurity", "APQC 8.0"),
    "FIN": ("Finance & accounting", "APQC 9.0"),
    "AST": ("Assets, facilities & maintenance", "APQC 10.0"),
    "RCL": ("Risk, compliance & legal", "APQC 11.0"),
    "PRC": ("Procurement & supply chain", "APQC 4.0 / 12.0"),
    "KNW": ("Knowledge & collaboration", "APQC 13.0"),
}
FUNCTION_ORDER = ["OPS", "CUS", "MKT", "FIN", "HR", "PRC", "RCL", "IT", "AST", "STR", "KNW"]

# task nature indices (opportunity_data.FAMILIES)
RPA, RULE, BI, IDP, GEN, RAG, CONV, VIS, ML, AGT = range(10)

# sector code -> name
SECTORS = {
    "XI": "Cross-industry", "BNK": "Banking & payments", "INS": "Insurance", "CAP": "Capital markets & wealth",
    "HLT": "Healthcare", "TEL": "Telecommunications", "GOV": "Government & public sector", "RET": "Retail & e-commerce",
    "HOS": "Hospitality & tourism", "MFG": "Manufacturing & industrial", "ENR": "Oil, gas, energy & utilities",
    "LOG": "Logistics, aviation & transport", "REC": "Real estate & construction", "EDU": "Education", "PRO": "Professional services",
}
SECTOR_ORDER = list(SECTORS)

# (function, nature, process / use case, typical pain point, GT recommendation, data needed, KPIs, regulatory & risk notes, minimum risk tier)
_L = {
"XI": [
 ("FIN", IDP, "Supplier invoice capture & posting", "Invoices keyed manually from PDF / email into the ERP",
  "Capture invoices with intelligent document processing, validate against PO and vendor master, post automatically; route exceptions to AP.",
  "Invoice PDFs / scans, vendor master, purchase orders", "Touchless invoice rate; cost per invoice; posting cycle time", "Segregation of duties in approval; vendor bank-detail change controls (payment fraud).", "Low"),
 ("FIN", RULE, "Three-way match & payment approval", "PO, goods receipt and invoice checked by hand",
  "Configure tolerance-based three-way matching in the ERP workflow; auto-approve within tolerance and escalate exceptions.",
  "POs, goods receipts, invoices", "Auto-match rate; late-payment penalties; exceptions per 100 invoices", "Approval limits and SoD must be enforced in the workflow.", "Low"),
 ("FIN", BI, "Bank reconciliations", "Spreadsheet matching every month",
  "Deploy a reconciliation tool with rule-based auto-matching; add ML-assisted fuzzy matching only once rules are exhausted.",
  "Bank statements (MT940 / CSV), GL cash entries", "Auto-match %; days to reconcile; unreconciled items ageing", "Reviewer sign-off retained; audit trail of matches.", "Low"),
 ("FIN", BI, "Intercompany reconciliation & eliminations", "Late intercompany agreements delay the close",
  "Standardise intercompany coding, automate matching and elimination journals in the consolidation tool.",
  "Intercompany ledgers, entity mapping", "Intercompany differences at close; close days", "-", "Low"),
 ("FIN", BI, "Month-end close & management packs", "Manual report packs delivered late",
  "Close-checklist workflow plus automated report packs (e.g., Power BI); GenAI drafts variance commentary for finance review.",
  "GL, budgets, KPI definitions", "Close days; report delivery date; manual adjustments", "GenAI commentary reviewed before release; no confidential data in public tools.", "Low"),
 ("FIN", ML, "Cash-flow forecasting", "Spreadsheet forecasts with poor accuracy",
  "Driver-based ML forecast using AR / AP history and seasonality; run in parallel with the manual forecast for three cycles before relying on it.",
  "2-3 years of AR / AP, bank and payroll history", "Forecast accuracy (MAPE); idle cash; borrowing cost", "Model owner and back-testing documented.", "Low"),
 ("FIN", RPA, "Collections & dunning", "Overdue invoices chased manually",
  "Automated dunning workflow with reminders by email / WhatsApp and promise-to-pay tracking; add payment-propensity scoring once history allows.",
  "AR ledger, customer contacts, payment history", "DSO; overdue %; collector productivity", "Fair-treatment and contact-time rules; customer consent for WhatsApp.", "Low"),
 ("FIN", RPA, "VAT return preparation", "Collating transactions and VAT codes by hand",
  "Automate extraction and validation of VAT-coded transactions and populate the NBR VAT return template; reviewer sign-off before filing.",
  "Sales / purchase ledgers, VAT codes", "Preparation hours; filing errors; penalties", "NBR VAT law compliance; maker-checker on filing.", "Low"),
 ("FIN", IDP, "Expense claims audit", "Receipts checked manually against policy",
  "Receipt capture with IDP, a rules engine for policy checks and duplicate / anomaly flags for review.",
  "Receipts, expense policy, card feeds", "Claims processed per FTE; policy breaches detected; reimbursement time", "Employee data - PDPL; transparent policy rules.", "Low"),
 ("FIN", GEN, "Financial statements & disclosure drafting", "Mapping trial balances and drafting notes manually",
  "Rules-based TB-to-line mapping with AI suggestions; GenAI drafts notes from approved templates; qualified accountant review and sign-off.",
  "Trial balance, prior-year FS, IFRS disclosure checklist", "Preparation hours; review points; restatements", "IFRS compliance; professional review mandatory; IESBA independence where an auditor provides it (GT AI FS tool - in preparation).", "Medium"),
 ("FIN", GEN, "Budget narratives & variance commentary", "Commentary written from scratch each month",
  "GenAI drafts budget and variance commentary from approved KPI tables; finance edits and approves.",
  "Budget vs actuals, KPI definitions", "Hours per pack; timeliness", "Confidential financials only in approved enterprise tools.", "Low"),
 ("FIN", RPA, "Fixed-asset register & depreciation", "Asset additions and disposals updated manually",
  "Automate asset creation from capex POs and depreciation runs; dashboard for physical-verification exceptions.",
  "Capex POs, asset register", "Register accuracy; close hours", "-", "Low"),
 ("HR", RULE, "Payroll input validation", "Attendance and allowances collated by hand",
  "Rules-based validation of payroll inputs (attendance, overtime, allowances) with exception reports before payroll run.",
  "Time & attendance, HRIS, allowance rules", "Payroll errors; re-runs; hours per cycle", "Employee personal data - PDPL; LMRA / labour-law rules.", "Low"),
 ("HR", ML, "CV screening & shortlisting", "High application volumes, slow shortlisting",
  "Start with structured screening criteria (rules). If ML / GenAI ranking is used: bias testing, human decision on every candidate, candidate notice and records.",
  "Job criteria, past applications and hiring outcomes", "Time to shortlist; quality of hire; adverse-impact ratio", "HIGH-RISK under EU AI Act Annex III (4) - employment; emotion recognition at work prohibited (Art. 5); PDPL; non-discrimination.", "High"),
 ("HR", RPA, "Interview scheduling", "Back-and-forth emails to schedule interviews",
  "Calendar-integrated scheduling automation with candidate self-booking.",
  "Interviewer calendars, candidate contacts", "Time to schedule; no-shows", "-", "Low"),
 ("HR", CONV, "Employee HR queries (leave, policies, payslips)", "HR answers the same questions repeatedly",
  "HR virtual agent grounded on HR policies plus self-service transactions via HRIS integration; hand-off to HR for sensitive cases.",
  "HR policies, HRIS APIs", "Query deflection; HR response time; employee satisfaction", "Disclose AI to users; access control on personal data.", "Low"),
 ("HR", RPA, "Onboarding & offboarding", "Many hand-offs across HR, IT and facilities",
  "Workflow orchestrating accounts, assets, payroll and training; automated timely access removal at exit.",
  "HRIS events, IT identity system", "Day-one readiness; orphan accounts; cycle time", "Access-removal is a key security control (ISO/IEC 27001 A.5.18).", "Low"),
 ("HR", GEN, "Job descriptions, policies & HR letters", "Time-consuming drafting",
  "GenAI drafting from approved templates and competency frameworks; HR review for bias and accuracy.",
  "Templates, competency framework", "Drafting time; consistency", "Check inclusive language; no personal data in prompts.", "Low"),
 ("HR", GEN, "Learning content & assessments", "Training content slow and costly to produce",
  "GenAI-assisted course outlines, micro-learning and quizzes from approved source material; SME validation.",
  "Policies, procedures, SME content", "Content production time; completion; scores", "Copyright of source material; accuracy review.", "Low"),
 ("HR", ML, "Attrition risk analytics", "Losing key staff without warning",
  "Aggregate attrition-driver analytics for HR planning; avoid individual automated decisions; transparency to employees.",
  "HRIS history, engagement survey results", "Regretted attrition; retention-plan coverage", "Profiling of employees - PDPL transparency; not used for adverse individual decisions.", "Medium"),
 ("HR", GEN, "Performance-review summarisation", "Managers struggle to summarise feedback",
  "GenAI summaries of 360 feedback for managers; manager remains author and decision-maker.",
  "Feedback text", "Time per review; quality of feedback", "Employment decisions - human decision mandatory; PDPL.", "Medium"),
 ("CUS", CONV, "Customer enquiries (web, app, WhatsApp, phone)", "Long waits for routine questions",
  "Bilingual (Arabic / English) virtual agent grounded on approved FAQs and account APIs, with seamless hand-off to staff.",
  "FAQs, product information, CRM / account APIs", "Containment rate; average handling time; CSAT", "Disclose AI interaction (EU AI Act Art. 50 where applicable); authentication before account data.", "Medium"),
 ("CUS", GEN, "Email & ticket triage and suggested replies", "Manual sorting and slow responses",
  "LLM classification and routing of incoming emails / tickets with suggested replies for agent approval.",
  "Historic tickets, routing rules", "First-response time; misrouted tickets; agent productivity", "Human approval of replies; PDPL.", "Low"),
 ("CUS", GEN, "Complaint handling & root-cause analysis", "Complaints triaged late; themes not visible",
  "GenAI categorisation, summarisation and theme analysis of complaints; deadlines tracked in workflow.",
  "Complaint records", "Resolution time; repeat complaints; regulatory breaches", "Sector complaint rules (e.g., CBB, TRA) - deadlines and reporting.", "Medium"),
 ("CUS", VIS, "Call summarisation & quality assurance", "Supervisors sample only a few calls",
  "Speech-to-text with automated call summaries, QA scoring against scripts and compliance phrases.",
  "Call recordings, QA scorecards", "Calls QA'd %; after-call work time; compliance breaches", "Recording consent; Arabic dialect accuracy testing; no emotion recognition of employees (EU AI Act Art. 5).", "Medium"),
 ("MKT", RAG, "Proposal, quotation & tender responses", "Re-writing similar content for every bid",
  "Knowledge assistant over approved credentials, CVs and past proposals to draft responses; bid manager review.",
  "Past proposals, credentials library, CVs", "Proposal preparation time; win rate", "Client confidentiality - sanitise past work; human review.", "Low"),
 ("MKT", ML, "Lead scoring & next-best action", "Sales effort spread evenly across leads",
  "ML lead scoring from CRM history with explainable drivers; sales retains judgement.",
  "CRM history with won / lost outcomes", "Conversion rate; sales cycle time", "Profiling - PDPL transparency and marketing consent.", "Low"),
 ("MKT", ML, "Customer churn prediction", "Customers leave without warning",
  "Churn model on usage and service history feeding retention campaigns; measure uplift with control groups.",
  "Customer, transaction and service history with churn outcomes", "Churn rate; retention-campaign uplift", "Consent for marketing use; fairness of offers.", "Medium"),
 ("MKT", GEN, "Marketing content & campaigns", "Slow content production",
  "GenAI-assisted copy, images and variants within brand guidelines; brand and legal approval.",
  "Brand guidelines, product information", "Content cycle time; engagement", "Copyright / IP; label synthetic media where required (EU AI Act Art. 50).", "Low"),
 ("MKT", GEN, "Arabic / English translation", "External translation cost and delays",
  "Enterprise machine translation with glossary and human post-editing for external documents.",
  "Glossaries, translation memories", "Turnaround; cost per word", "Legal / regulatory texts need certified human review.", "Low"),
 ("MKT", GEN, "Social listening & review sentiment", "Customer feedback not analysed",
  "GenAI sentiment and theme analysis across reviews and social channels with dashboard.",
  "Public reviews, social feeds, survey text", "Response time to issues; NPS drivers identified", "Use public / consented data only.", "Low"),
 ("MKT", ML, "Customer segmentation & personalised offers", "One-size-fits-all campaigns",
  "ML segmentation and propensity models driving personalised offers, with consent management.",
  "Transaction and demographic data, campaign responses", "Campaign conversion; revenue per customer", "Profiling - PDPL consent; avoid sensitive attributes; fairness.", "Medium"),
 ("PRC", RPA, "Purchase requisition to order", "Approvals chased by email",
  "Digital requisition workflow with catalogue buying, approval matrix and automatic PO creation.",
  "Catalogues, approval matrix, vendor master", "PR-to-PO cycle time; maverick spend", "Delegation-of-authority rules enforced.", "Low"),
 ("PRC", IDP, "Supplier onboarding & due diligence", "Collecting documents and checks manually",
  "Supplier portal with IDP of CR / licences / bank letters, sanctions screening and risk scoring.",
  "Supplier documents, sanctions lists", "Onboarding time; incomplete files; screening coverage", "Third-party risk policy; sanctions compliance.", "Low"),
 ("PRC", GEN, "Contract review & obligation tracking", "Missed renewals and unfavourable terms",
  "GenAI clause extraction against a playbook, obligation and renewal calendar; legal review of deviations.",
  "Contracts, clause playbook", "Review time; missed renewals; off-playbook terms", "Legal privilege and confidentiality; accuracy review.", "Medium"),
 ("PRC", BI, "Spend analytics & classification", "No single view of spend",
  "Spend cube with automated classification (UNSPSC); ML classification for free-text lines later.",
  "AP and PO data", "Spend under management; savings identified", "-", "Low"),
 ("PRC", ML, "Demand forecasting & inventory planning", "Stock-outs and excess stock",
  "ML demand forecasting with promotions / seasonality and automated replenishment proposals.",
  "2+ years of sales, inventory and promotion data", "Forecast accuracy; stock-outs; inventory days", "-", "Low"),
 ("PRC", GEN, "Tender evaluation support", "Evaluating long bids is slow",
  "GenAI summarises bids against criteria and flags gaps; evaluation committee scores and decides.",
  "Tender documents, bids, evaluation criteria", "Evaluation time; consistency", "Fairness and procurement law - human decision; bidder confidentiality.", "Medium"),
 ("RCL", RAG, "Regulatory change monitoring", "Tracking new rules manually",
  "Knowledge assistant monitoring regulator publications (e.g., CBB, NBR, PDPL guidance) and summarising impacts for compliance review.",
  "Regulator websites / rulebooks, obligations register", "Time to impact assessment; missed changes", "Summaries verified by Compliance against source text.", "Low"),
 ("RCL", RAG, "Policy & procedure Q&A", "Staff unsure where rules are",
  "Grounded assistant over approved policies with citations and access control.",
  "Current policies and procedures", "Queries answered; policy breaches", "Content ownership and versioning; hallucination testing.", "Low"),
 ("RCL", ML, "Internal-audit analytics (full-population testing)", "Sample-based testing of large populations",
  "Rules-based full-population tests plus ML anomaly detection to target audit work.",
  "ERP transaction data, master data", "Coverage %; exceptions found; audit hours", "Auditor judgement retained; analytics documented in working papers.", "Medium"),
 ("RCL", GEN, "Third-party risk questionnaires & SOC reports", "Vendor assessments take weeks",
  "GenAI pre-reviews vendor questionnaires and assurance reports against control requirements; analyst concludes.",
  "Questionnaires, SOC 2 / ISO certificates", "Assessment time; backlog", "Analyst accountable for rating; vendor-data confidentiality.", "Low"),
 ("RCL", GEN, "Business continuity plans & BIA", "Plans generic and outdated",
  "AI-assisted BIA, ISO 22301-aligned plan drafting and scenario exercises; owners validate (GT AI-powered BCP tool - in preparation).",
  "Process inventory, dependencies, RTO / RPO", "Plan currency; exercise frequency; recovery-time gaps", "Sector BCM rules (e.g., CBB); human validation of plan content.", "Medium"),
 ("RCL", RAG, "Legal research & precedent search", "Lawyers search manually across sources",
  "Legal research assistant over licensed legal databases and internal precedents with citations.",
  "Licensed legal content, precedents", "Research time; citation accuracy", "Verify citations; legal privilege.", "Medium"),
 ("RCL", GEN, "Board papers & minutes", "Minutes slow; papers inconsistent",
  "GenAI drafts minutes and paper summaries within an approved, access-controlled environment; company secretary approves.",
  "Agendas, papers, transcripts", "Minutes turnaround; action tracking", "Highly confidential - enterprise tool only; records retention.", "Medium"),
 ("RCL", RPA, "Data-subject requests (PDPL)", "Requests handled ad hoc",
  "DSR workflow with identity verification, data discovery search and deadline tracking.",
  "Systems inventory, request records", "Requests closed on time", "PDPL data-subject rights.", "Low"),
 ("IT", CONV, "IT service desk", "Repetitive password and access requests",
  "Virtual agent with automated password resets and access requests via ITSM integration.",
  "ITSM tickets, knowledge base", "Tickets deflected; MTTR; first-contact resolution", "Strong identity verification for resets.", "Low"),
 ("IT", RULE, "User access reviews", "Manual reconciliation of access lists",
  "Automated access-review campaigns with role rules and SoD conflict detection.",
  "IAM / AD exports, role matrix", "Review completion; orphan accounts; SoD conflicts", "ISO/IEC 27001 A.5.15-5.18.", "Low"),
 ("IT", AGT, "Security alert triage (SOC)", "Alert fatigue; slow investigations",
  "Security copilot for alert enrichment and triage; automated containment only for pre-approved playbooks with human approval for high-impact actions.",
  "SIEM / EDR alerts, threat intelligence", "MTTD / MTTR; analyst alerts per day; false positives", "Least agency and privilege, logging and kill-switch (ISACA Securing AI Agents 2026).", "Medium"),
 ("IT", GEN, "Code assistance & documentation", "Slow development; little documentation",
  "AI coding assistant within a secure SDLC: code review, secret scanning and licence checks on AI-generated code.",
  "Code repositories, standards", "Cycle time; defects; documentation coverage", "No secrets in prompts; IP / licence risk; OWASP LLM risks.", "Low"),
 ("IT", ML, "Vulnerability prioritisation", "Too many vulnerabilities to patch",
  "Risk-based prioritisation combining exploitability (e.g., EPSS), asset criticality and exposure.",
  "Vulnerability scans, asset inventory", "Mean time to remediate critical; risk reduction", "-", "Low"),
 ("IT", RPA, "IT asset & licence management", "Licences over-bought; assets untracked",
  "Automated discovery and licence reconciliation with renewal alerts.",
  "Discovery data, contracts", "Licence savings; asset accuracy", "-", "Low"),
 ("STR", BI, "KPI dashboards", "No single view of performance",
  "Governed KPI definitions and dashboards on a common data model; GenAI 'ask your data' later.",
  "Source-system data, KPI dictionary", "Report preparation time; data-quality issues", "Data ownership and definitions agreed first.", "Low"),
 ("STR", GEN, "Meeting minutes & action tracking", "Minutes late; actions lost",
  "Enterprise meeting assistant for transcripts, summaries and action tracking (with participant notice).",
  "Meeting audio / transcripts", "Minutes turnaround; actions closed on time", "Participant consent; confidential meetings excluded.", "Low"),
 ("STR", GEN, "Market & competitor research", "Research takes days",
  "GenAI research assistant with source citations for market scans; analyst verifies.",
  "Public sources, subscriptions", "Research time", "Verify sources; avoid confidential data in public tools.", "Low"),
 ("KNW", RAG, "Enterprise knowledge search", "Time lost looking for documents",
  "Permission-aware enterprise search / knowledge assistant over the document-management system.",
  "Organised document repository with access control", "Search time; reuse", "Respect existing permissions - over-sharing is the main risk.", "Low"),
 ("KNW", GEN, "Email & document drafting", "Routine drafting effort",
  "Enterprise GenAI assistant (e.g., Copilot) under an acceptable-use policy and training.",
  "None beyond user content", "Time saved per user; adoption", "Acceptable-use policy, data classification and human review.", "Low"),
 ("KNW", IDP, "Document classification & retention", "Documents unclassified; retention not applied",
  "Auto-classification and sensitivity labelling of documents with retention rules.",
  "Document repository, classification scheme", "Labelled documents %; retention compliance", "Supports data classification for AI (ISACA 2026; ISO/IEC 42001 A.7).", "Low"),
 ("AST", RPA, "Facilities requests & maintenance tickets", "Requests by phone and email",
  "Facilities service portal with automated routing and SLA tracking.",
  "Request history, asset list", "Response time; SLA compliance", "-", "Low"),
 ("AST", ML, "Building energy management", "High utility bills",
  "ML-based HVAC and lighting optimisation from BMS data (ISO 50001-aligned).",
  "BMS / meter data, occupancy", "kWh saved; cost; emissions", "-", "Low"),
],
"BNK": [
 ("OPS", IDP, "Retail customer onboarding (eKYC)", "Branch visits and manual document checks",
  "Digital onboarding: ID capture (CPR / passport), liveness check, automated screening and risk rating; analyst reviews exceptions.",
  "ID documents, selfie / liveness, customer data", "Onboarding time; drop-off rate; KYC exceptions", "CBB Rulebook FC (financial crime) KYC; biometric data - treat as sensitive (PDPL); liveness-vendor assurance.", "Medium"),
 ("RCL", ML, "Sanctions & PEP screening alert review", "High false-positive name matches",
  "Tune name-matching, then ML / GenAI-assisted alert disposition with evidence summary; analyst decides.",
  "Screening alerts with dispositions, customer data", "False-positive rate; alerts per analyst; time to clear", "CBB FC; FATF; model validation; never auto-close true-match candidates.", "Medium"),
 ("RCL", ML, "AML transaction-monitoring alert triage", "Investigators overwhelmed by false positives",
  "ML alert prioritisation on top of rule scenarios; investigators focus on high-risk alerts; challenger testing before go-live.",
  "2+ years of alerts with investigation outcomes, transactions, KYC", "False-positive reduction; SAR conversion; backlog", "CBB FC; FATF; model risk management (SR 11-7 principles); explainability to regulator.", "Medium"),
 ("RCL", GEN, "Suspicious transaction report (STR) narratives", "Narratives slow and inconsistent",
  "GenAI drafts STR narratives from case evidence in a secured environment; MLRO reviews and files.",
  "Case files, transactions", "Time per STR; quality findings", "Tipping-off confidentiality; enterprise tool only; MLRO accountability.", "Medium"),
 ("OPS", ML, "Retail credit decisioning", "Slow, inconsistent credit decisions",
  "Explainable scorecard / ML credit model with policy rules, reason codes and human review of declines; bias and stability testing.",
  "Application data, bureau data, repayment history", "Decision time; default rate; approval rate by segment", "HIGH-RISK: EU AI Act Annex III 5(b) creditworthiness of natural persons; CBB credit-risk rules; fair-lending; model validation.", "High"),
 ("OPS", GEN, "SME credit memo drafting", "Relationship managers spend days on memos",
  "GenAI drafts credit memos from financial statements and account data using the bank template; credit officer reviews.",
  "Financial statements, account conduct, templates", "Memo preparation time; turnaround to decision", "Decision stays with credit committee; data confidentiality.", "Medium"),
 ("OPS", IDP, "Trade-finance document checking (LCs)", "Manual checking of LCs and shipping documents",
  "IDP extracts LC and shipping-document data and checks discrepancies against UCP 600 / ISBP rules; checker confirms.",
  "LCs, bills of lading, invoices", "Documents checked per day; discrepancy-detection rate", "Sanctions / dual-use screening of goods and vessels.", "Low"),
 ("OPS", ML, "Card & payment fraud detection", "Fraud found late; customer losses",
  "Real-time ML fraud scoring with step-up authentication; continuous model monitoring for drift.",
  "Transaction history with confirmed fraud labels, device data", "Fraud losses (bps); false-decline rate; detection latency", "PCI DSS; customer-friction trade-off; model validation.", "Medium"),
 ("OPS", RULE, "Payment exceptions & repairs", "Failed payments repaired manually",
  "Rules-based auto-repair of common payment errors (IBAN, BIC, format) with exception queue.",
  "Payment messages (ISO 20022), repair history", "STP rate; repair time", "Four-eyes on high-value payments.", "Low"),
 ("CUS", CONV, "Banking virtual assistant", "Call centre peaks; routine balance and card queries",
  "Authenticated bilingual virtual assistant for balances, card controls and FAQs; no financial advice; hand-off to agents.",
  "FAQs, core-banking APIs", "Containment; AHT; CSAT", "Authentication; disclose AI; CBB business-conduct and complaints rules.", "Medium"),
 ("CUS", GEN, "Complaints handling (CBB timelines)", "Complaints categorised late; deadlines missed",
  "GenAI categorisation and draft responses with workflow deadline tracking and root-cause reporting.",
  "Complaint records", "On-time resolution; repeat complaints", "CBB complaints-handling requirements; human-approved responses.", "Medium"),
 ("OPS", ML, "Collections prioritisation", "Collectors call all accounts equally",
  "ML roll-rate models prioritise accounts and channel; treatment strategies approved by credit risk.",
  "Delinquency history, contact outcomes", "Roll rates; cure rate; cost to collect", "Fair treatment of customers; avoid sensitive attributes.", "Medium"),
 ("RCL", BI, "Regulatory reporting (CBB returns)", "Manual population and reconciliation of returns",
  "Automated data lineage, validation rules and return population with reconciliation to GL (BCBS 239 principles).",
  "Core-banking, GL, risk data", "Resubmissions; preparation hours; data-quality breaks", "CBB reporting accuracy; maker-checker.", "Low"),
 ("FIN", ML, "Liquidity & cash forecasting (treasury)", "Buffers held conservatively",
  "ML forecasting of deposit flows and liquidity needs feeding ALCO, alongside regulatory metrics.",
  "Deposit / loan flows history", "Forecast accuracy; excess buffer cost", "Model validation; ALCO oversight.", "Medium"),
 ("AST", ML, "ATM & branch cash forecasting", "Cash-outs and idle cash",
  "ML cash-demand forecasting and optimised replenishment schedules.",
  "ATM withdrawals history, calendar effects", "Cash-out incidents; idle cash; CIT cost", "-", "Low"),
 ("OPS", IDP, "Corporate onboarding (KYB)", "Corporate KYC files take weeks",
  "IDP of commercial registration and constitutional documents, ownership-structure extraction and GenAI file summary for the analyst.",
  "CR documents, shareholder registers", "Onboarding time; incomplete files", "UBO identification (CBB FC; FATF R.24).", "Medium"),
 ("OPS", IDP, "Cheque & instruction processing", "Manual keying of instructions",
  "IDP with signature-verification support and maker-checker for exceptions.",
  "Cheque images, mandates", "STP rate; errors", "Fraud controls on signature mismatch.", "Low"),
 ("MKT", RAG, "Relationship-manager meeting preparation", "RMs gather information from many systems",
  "RM assistant summarising client relationship, products and news before meetings.",
  "CRM, product holdings, news", "Prep time; cross-sell", "Access control by RM portfolio; confidentiality.", "Low"),
 ("RCL", GEN, "Model documentation & validation reports", "Model documentation lags behind changes",
  "GenAI drafts model documentation from code and test results; validators review.",
  "Model code, test results, templates", "Documentation backlog; validation cycle time", "Model risk policy; independence of validation.", "Low"),
 ("CUS", AGT, "Card dispute & chargeback handling", "Disputes handled across several systems",
  "Supervised agent gathers transaction evidence, pre-fills scheme forms and proposes outcome; staff approve submission.",
  "Transactions, scheme rules, customer messages", "Dispute cycle time; win rate; scheme deadlines met", "Card-scheme rules; human approval of every submission; agent least privilege.", "Medium"),
 ("RCL", ML, "IFRS 9 ECL staging & overlays support", "Manual staging overrides and overlays",
  "ML early-warning indicators to support significant-increase-in-credit-risk staging; overlays documented.",
  "Loan performance history, macro data", "Staging accuracy; overlay size", "Model risk management; auditor and CBB scrutiny.", "Medium"),
 ("RCL", AGT, "Periodic KYC refresh", "KYC refresh backlog",
  "Supervised agent collects updated data, pre-fills the review and flags changes in risk; analyst approves.",
  "KYC files, transaction profile, screening", "Backlog; refresh time", "CBB FC; analyst accountable; agent audit trail.", "Medium"),
 ("OPS", IDP, "Mortgage document verification", "Salary certificates and title deeds checked manually",
  "IDP with authenticity checks and data comparison against application.",
  "Salary certificates, title deeds, valuations", "Processing time; fraud detected", "Document-fraud controls.", "Low"),
],
"INS": [
 ("CUS", IDP, "Claims first notification of loss (FNOL)", "Claim forms keyed manually",
  "Digital FNOL with IDP of forms and photos, automatic policy validation and claim creation.",
  "Claim forms, policy data", "FNOL-to-registration time; data errors", "PDPL; health data in medical claims is sensitive.", "Low"),
 ("OPS", VIS, "Motor damage assessment from photos", "Surveyor visits for minor claims",
  "Computer-vision damage estimation for low-value motor claims with adjuster approval.",
  "Labelled damage photos, repair costs", "Cycle time; leakage; customer satisfaction", "Explain decisions; human review of declines.", "Medium"),
 ("RCL", ML, "Claims fraud detection", "Fraud detected late or not at all",
  "ML / network analytics fraud scoring to refer suspicious claims to SIU; no automatic rejection.",
  "Claims history with confirmed fraud outcomes", "Fraud savings; referral hit rate", "Fair treatment; human decision; model validation.", "Medium"),
 ("OPS", RULE, "Fast-track settlement of low-value claims", "Simple claims queue behind complex ones",
  "Rules-based straight-through settlement for low-value, low-risk claims; ML triage added later.",
  "Claims data, coverage rules", "STP rate; settlement time", "Authority limits; audit sampling.", "Low"),
 ("OPS", IDP, "Medical claims adjudication", "Invoices and codes checked manually",
  "IDP of invoices, coding-validation rules and anomaly flags (e.g., upcoding) for adjudicators.",
  "Medical invoices, ICD / CPT codes, provider contracts", "Adjudication time; leakage; provider disputes", "Health data - sensitive under PDPL; NHRA provider rules.", "Medium"),
 ("OPS", IDP, "Commercial underwriting submissions", "Broker submissions read manually",
  "IDP extracts risk data from broker submissions into the underwriting workbench with GenAI summary.",
  "Submissions, schedules, loss runs", "Quote turnaround; submissions handled per underwriter", "Underwriter decision retained.", "Low"),
 ("OPS", ML, "Life & health underwriting risk scoring", "Slow medical underwriting",
  "Explainable risk-scoring support for underwriters with bias testing and documented overrides.",
  "Applications, medical disclosures, claims experience", "Decision time; loss ratio", "HIGH-RISK: EU AI Act Annex III 5(c) risk assessment & pricing in life and health insurance; health data; CBB.", "High"),
 ("OPS", ML, "Motor pricing & renewal optimisation", "Static tariffs; retention losses",
  "ML risk models within actuarially approved pricing; fairness checks across customer groups.",
  "Policy, claims, telematics (if any)", "Loss ratio; retention", "CBB pricing rules; avoid prohibited attributes.", "Medium"),
 ("OPS", RPA, "Policy servicing (endorsements, certificates)", "Endorsements keyed manually",
  "Automate endorsements and certificate issuance via portal and RPA.",
  "Policy admin system", "Turnaround; errors", "-", "Low"),
 ("CUS", CONV, "Policyholder virtual assistant", "Calls on claim status and documents",
  "Virtual assistant for claim status, documents and FAQs; hand-off to agents.",
  "Claims / policy APIs, FAQs", "Containment; CSAT", "Disclose AI; authentication.", "Medium"),
 ("MKT", RAG, "Broker / agent support assistant", "Brokers wait for product answers",
  "Grounded assistant over product wordings and underwriting guidelines for brokers and agents.",
  "Wordings, guidelines", "Response time; broker satisfaction", "Answers cite wording; no binding of cover by AI.", "Low"),
 ("FIN", IDP, "Reinsurance bordereaux processing", "Spreadsheets in many formats",
  "IDP / data-transformation pipeline standardising bordereaux and validating against treaties.",
  "Bordereaux files, treaty terms", "Processing time; reconciliation breaks", "-", "Low"),
 ("FIN", BI, "IFRS 17 data preparation & reconciliation", "Manual data preparation each quarter",
  "Automated data pipelines, validation and reconciliation dashboards for IFRS 17.",
  "Policy, claims, finance data", "Close time; reconciliation breaks", "Audit trail.", "Low"),
 ("OPS", GEN, "Policy wording comparison", "Comparing wordings clause by clause",
  "GenAI comparison of wordings against the standard with highlighted deviations for legal review.",
  "Wordings, standard clauses", "Review time", "Legal review of conclusions.", "Low"),
 ("FIN", ML, "Subrogation & recovery identification", "Recovery opportunities missed",
  "ML flags claims with recovery potential from claim notes and data.",
  "Claims notes and recovery history", "Recovery amount; identification rate", "-", "Low"),
 ("RCL", RAG, "Takaful / Sharia-compliance research", "Scholars' rulings hard to search",
  "Knowledge assistant over approved Sharia board resolutions and standards with citations.",
  "Sharia board resolutions, AAOIFI standards", "Research time", "Sharia supervisory board remains decision-maker.", "Low"),
 ("RCL", BI, "Catastrophe & accumulation monitoring", "Exposure not visible by location",
  "Geospatial accumulation dashboards and alerts against limits.",
  "Policy locations, sums insured", "Limit breaches; reporting time", "-", "Low"),
],
"CAP": [
 ("OPS", RULE, "Trade confirmation & settlement exceptions", "Breaks resolved manually",
  "Rules-based matching and exception workflows; predictive settlement-fail flags later.",
  "Trade, confirmation and settlement messages", "STP rate; fails; break ageing", "-", "Low"),
 ("RCL", ML, "Market-abuse surveillance alert triage", "High alert volumes",
  "ML prioritisation and GenAI case summaries on top of surveillance scenarios; compliance decides.",
  "Orders, trades, communications, alert outcomes", "False positives; time per alert", "CBB capital-market rules; model validation.", "Medium"),
 ("MKT", GEN, "Research summarisation & earnings-call analysis", "Analysts read hundreds of pages",
  "GenAI summaries and Q&A over filings and call transcripts with citations.",
  "Filings, transcripts", "Analyst time; coverage", "Verify figures; MNPI controls.", "Low"),
 ("FIN", BI, "Fund NAV reconciliation", "Manual NAV checks",
  "Automated NAV reconciliation and tolerance checks with exception dashboards.",
  "Custodian and administrator data", "Reconciliation time; NAV errors", "-", "Low"),
 ("CUS", GEN, "Client reporting & factsheets", "Reports assembled by hand",
  "Automated report data plus GenAI-drafted commentary reviewed by portfolio managers.",
  "Portfolio data, market data", "Production time; errors", "Marketing-communication rules; review before issue.", "Low"),
 ("OPS", IDP, "Investor onboarding & KYC", "Subscription documents checked manually",
  "IDP of subscription documents and KYC data with automated screening.",
  "Subscription forms, ID documents", "Onboarding time", "CBB FC; FATF.", "Medium"),
 ("RCL", IDP, "ESG data extraction from reports", "ESG data collected manually",
  "IDP / GenAI extraction of ESG metrics from company reports into the ESG database.",
  "Sustainability reports", "Coverage; extraction accuracy", "Verify against source; disclosure standards (ISSB).", "Low"),
 ("OPS", RULE, "Portfolio compliance & rebalancing alerts", "Limit breaches found late",
  "Pre- and post-trade rules engine with automated rebalancing proposals.",
  "Holdings, mandates, limits", "Breaches; time to detect", "-", "Low"),
],
"HLT": [
 ("CUS", CONV, "Appointment booking & reminders", "No-shows and phone-booking queues",
  "WhatsApp / web booking assistant integrated with the scheduling system and automated reminders.",
  "Schedules, patient contacts", "No-show rate; call volume; booking time", "Patient data - sensitive (PDPL); consent for messaging.", "Medium"),
 ("OPS", RPA, "Patient registration & insurance eligibility", "Manual eligibility checks at reception",
  "Automated eligibility verification with payers and pre-filled registration.",
  "Patient demographics, payer portals", "Registration time; claim rejections for eligibility", "Patient data protection.", "Medium"),
 ("OPS", IDP, "Prior-authorisation requests", "Forms and clinical documents compiled manually",
  "IDP assembles prior-authorisation packs from the EHR; staff verify and submit.",
  "EHR data, payer forms", "Authorisation turnaround; denials", "Health data; human submission.", "Medium"),
 ("FIN", GEN, "Medical coding assistance (ICD-10 / CPT)", "Coding backlog and errors",
  "AI-suggested codes from clinical documentation for certified coders to confirm.",
  "Clinical notes, coding history", "Coder productivity; coding accuracy; denials", "Coders remain accountable; audit sampling.", "Medium"),
 ("FIN", RPA, "Claims submission & denial management", "Denials reworked manually",
  "Automated claim scrubbing and submission; denial-prediction model once history allows.",
  "Claims and remittance history", "First-pass acceptance; days in AR", "-", "Medium"),
 ("OPS", VIS, "Clinical documentation (ambient scribe)", "Clinicians typing notes",
  "Ambient speech-to-note drafting in the EHR; clinician reviews and signs every note.",
  "Consultation audio, note templates", "Documentation time; clinician satisfaction", "Patient consent; NHRA rules; health data; clinician sign-off.", "Medium"),
 ("OPS", GEN, "Discharge summaries & referral letters", "Letters delayed after discharge",
  "GenAI drafts from the EHR record for clinician approval.",
  "EHR record", "Time to discharge summary; completeness", "Clinical accuracy review; health data.", "Medium"),
 ("OPS", VIS, "Radiology image triage", "Reporting backlogs",
  "Regulated (cleared) AI triage software prioritising worklists; radiologist reports every study.",
  "Imaging studies (DICOM) with reports", "Turnaround for critical findings; backlog", "Medical-device AI: NHRA registration; EU MDR / FDA clearance; EU AI Act Annex I high-risk.", "High"),
 ("OPS", ML, "Patient deterioration early warning", "Late recognition of deterioration (e.g., sepsis)",
  "Validated early-warning model in the EHR with clinical escalation protocol; local validation before go-live.",
  "Vital signs, labs, outcomes", "Time to intervention; ICU transfers; alert burden", "Clinical decision support - medical-device rules may apply; bias and alert-fatigue testing.", "High"),
 ("OPS", ML, "Bed & capacity management", "Bed shortages and delays",
  "Admission / discharge forecasting with bed-management dashboard.",
  "ADT history", "Bed occupancy; ED boarding time", "-", "Low"),
 ("PRC", ML, "Pharmacy inventory & expiry", "Stock-outs and expired drugs",
  "Demand forecasting and expiry alerts for pharmacy stock.",
  "Dispensing and stock history", "Stock-outs; expiry write-offs", "Controlled-drug rules unaffected.", "Low"),
 ("OPS", RULE, "Lab critical-value alerts & result routing", "Critical results communicated late",
  "Rules-based routing and escalation of critical values with acknowledgement tracking.",
  "LIS results, escalation rules", "Time to acknowledgement", "Patient safety - validated rules.", "Medium"),
 ("CUS", CONV, "Patient enquiries (non-clinical)", "Call centre overloaded with routine questions",
  "Virtual assistant for directions, preparation instructions, billing; no symptom triage.",
  "FAQs, service information", "Containment; call volumes", "Clear boundary: no medical advice; disclose AI.", "Medium"),
 ("KNW", RAG, "Clinical guideline Q&A for staff", "Staff search protocols manually",
  "Grounded assistant over approved clinical guidelines and protocols with citations.",
  "Approved guidelines", "Time to answer; protocol adherence", "Content governance; clinician judgement; not for diagnosis.", "Medium"),
 ("FIN", BI, "Revenue-cycle analytics", "No view of leakage",
  "Revenue-cycle dashboards on charges, denials and collections.",
  "Billing and claims data", "Leakage identified; days in AR", "-", "Low"),
 ("OPS", IDP, "Medical-records digitisation", "Paper records hard to retrieve",
  "Scanning with IDP indexing into the EHR / document system.",
  "Paper records", "Retrieval time; records digitised", "Health data security; retention rules.", "Medium"),
 ("HR", ML, "Staff rostering optimisation", "Rosters built manually; overtime high",
  "Optimisation-based rostering respecting skills, rules and preferences.",
  "Demand patterns, staff skills, rules", "Overtime; vacancy fill; staff satisfaction", "Fairness and labour rules.", "Low"),
 ("CUS", GEN, "Patient-feedback analysis", "Feedback not analysed",
  "GenAI theme and sentiment analysis of patient feedback.",
  "Survey and complaint text", "Themes actioned; satisfaction", "De-identify patient data.", "Low"),
 ("KNW", RAG, "Research & literature review", "Literature reviews take weeks",
  "Research assistant over licensed literature databases with citations.",
  "Licensed databases", "Review time", "Verify citations; research ethics.", "Low"),
 ("CUS", CONV, "Post-discharge follow-up", "Follow-up calls not made",
  "Automated follow-up messages with escalation to nurses on red-flag answers.",
  "Discharge lists, question protocol", "Readmissions; follow-up coverage", "Clinical escalation protocol; patient consent.", "Medium"),
],
"TEL": [
 ("AST", ML, "Network fault prediction & predictive maintenance", "Outages detected by customers",
  "ML on network telemetry to predict faults and trigger proactive maintenance.",
  "Alarm and performance history, tickets", "Network availability; MTTR; truck rolls", "Critical infrastructure - resilience controls.", "Medium"),
 ("OPS", ML, "Alarm correlation & root cause (AIOps)", "NOC flooded with alarms",
  "AIOps correlation and probable-root-cause suggestions for NOC engineers.",
  "Alarms, topology, incident history", "Alarm reduction; MTTR", "-", "Low"),
 ("MKT", ML, "Churn prediction & retention offers", "Postpaid churn at contract end",
  "Churn propensity with next-best-retention-offer and controlled experiments.",
  "Usage, billing, care interactions, churn labels", "Churn rate; retention ROI", "Consent for marketing; fairness of offers; TRA consumer rules.", "Medium"),
 ("CUS", CONV, "Customer-care virtual agent", "Calls on bills, plans and roaming",
  "Bilingual virtual agent with account integration for bills, plans and troubleshooting.",
  "FAQs, BSS / OSS APIs", "Containment; AHT; CSAT", "Disclose AI; authentication; TRA consumer protection.", "Medium"),
 ("OPS", ML, "Field-force dispatch & scheduling", "Inefficient technician routing",
  "Optimisation of dispatch and routes with skills and SLA constraints.",
  "Work orders, locations, skills", "Jobs per technician; SLA met", "-", "Low"),
 ("OPS", RPA, "Order-to-activation provisioning", "Orders re-keyed across systems",
  "End-to-end order orchestration with RPA for legacy steps.",
  "Order and provisioning systems", "Activation time; fallout rate", "-", "Low"),
 ("CUS", RULE, "Billing disputes & adjustments", "Disputes handled case by case",
  "Rules-based adjustment approval within limits; GenAI case summary for complex disputes.",
  "Billing records, dispute history", "Resolution time; adjustment leakage", "Approval limits.", "Low"),
 ("FIN", ML, "Revenue assurance & leakage detection", "Unbilled usage and rating errors",
  "Automated reconciliation of network usage to billing with ML anomaly detection.",
  "CDRs, billing data", "Leakage recovered; detection time", "-", "Low"),
 ("RCL", ML, "Telecom fraud detection (SIM-swap, IRSF, wangiri)", "Fraud losses and customer account takeovers",
  "Real-time fraud scoring with automated blocking rules for high-confidence patterns and analyst review.",
  "CDRs, SIM events, fraud cases", "Fraud losses; detection time; false blocks", "Customer-impact review; TRA requirements.", "Medium"),
 ("MKT", ML, "Next-best offer & personalisation", "Generic offers",
  "Propensity models and offer engine across app and care channels.",
  "Usage and campaign history", "Take-up rate; ARPU uplift", "Consent and profiling transparency (PDPL).", "Medium"),
 ("CUS", VIS, "Contact-centre speech analytics", "Limited QA coverage",
  "Speech analytics for 100% call QA, topic trends and compliance.",
  "Call recordings", "QA coverage; repeat calls", "Recording consent; no employee emotion recognition.", "Medium"),
 ("STR", ML, "Network capacity planning", "Capacity added late or early",
  "Traffic forecasting by cell and site for capex planning.",
  "Traffic history, growth drivers", "Congested cells; capex efficiency", "-", "Low"),
 ("AST", IDP, "Site lease & tower document management", "Lease terms scattered",
  "IDP abstraction of site leases with renewal and payment alerts.",
  "Lease documents", "Missed renewals; abstraction time", "-", "Low"),
 ("RCL", BI, "Regulatory & QoS reporting (TRA)", "Manual compilation of returns",
  "Automated QoS and regulatory reporting pipelines with validation.",
  "Network KPIs, customer data", "Reporting time; resubmissions", "TRA reporting accuracy.", "Low"),
 ("CUS", AGT, "Agentic self-service (plan changes, troubleshooting)", "Customers need an agent for simple changes",
  "Supervised agent executing plan changes and guided troubleshooting within strict permissions; confirmation before any charge.",
  "BSS / OSS APIs, product catalogue", "Self-service completion; cost per contact", "Least privilege; customer confirmation; logging (ISACA 2026; OWASP LLM06).", "Medium"),
 ("OPS", IDP, "SIM registration & ID verification", "Manual ID checks in stores",
  "ID capture and verification with automated data entry; staff confirm.",
  "ID documents", "Registration time; errors", "Telecom KYC / SIM-registration requirements; biometric data sensitive.", "Medium"),
 ("IT", GEN, "Network-configuration change co-pilot", "Change errors cause outages",
  "GenAI reviews configuration changes against standards and drafts method statements; engineer approves.",
  "Configs, standards, change history", "Change failure rate", "No autonomous changes on production network.", "Medium"),
],
"GOV": [
 ("CUS", CONV, "Citizen enquiries (multi-channel)", "Call-centre peaks; repeated questions",
  "Bilingual virtual assistant grounded on official service information with hand-off to staff.",
  "Service catalogue, FAQs", "Containment; waiting time; satisfaction", "Disclose AI; accessibility; iGA AI policy.", "Medium"),
 ("OPS", IDP, "Permit & licence application processing", "Paper-heavy applications and checks",
  "Digital application with IDP of attachments and rules-based completeness checks; officer decides.",
  "Application forms, attachments, rules", "Processing time; returned applications", "Transparency of decisions; appeal route.", "Medium"),
 ("OPS", RULE, "Eligibility assessment for services / benefits", "Inconsistent eligibility checks",
  "Transparent rules engine for eligibility with human review of refusals; ML only with full impact assessment.",
  "Policy rules, applicant data", "Processing time; error rate; appeals", "HIGH-RISK: EU AI Act Annex III 5(a) eligibility for public assistance; fairness, explainability.", "High"),
 ("OPS", ML, "Risk-based inspection targeting", "Inspections not risk-based",
  "Risk scoring of premises / entities to prioritise inspections; inspectors retain discretion.",
  "Inspection history, outcomes", "Hit rate; inspections per inspector", "Fairness; explainable criteria.", "Medium"),
 ("STR", GEN, "Correspondence & briefing notes", "Drafting consumes senior time",
  "GenAI drafting of letters and briefing notes in a government-approved environment.",
  "Templates, prior correspondence", "Drafting time", "Classified data never in public tools; iGA policy.", "Medium"),
 ("RCL", RAG, "Policy & legislation research", "Research across many sources",
  "Research assistant over legislation, decrees and policies with citations.",
  "Official gazette, policies", "Research time", "Verify against official sources.", "Low"),
 ("MKT", GEN, "Official translation (Arabic / English)", "Translation backlog",
  "Machine translation with terminology control and certified human review.",
  "Glossaries, prior translations", "Turnaround; cost", "Legal validity requires human review.", "Medium"),
 ("PRC", GEN, "Government tender evaluation support", "Evaluation slow",
  "GenAI summaries of bids against criteria; committee scores and decides.",
  "Tender documents and bids", "Evaluation time", "Tender Board rules; fairness; confidentiality.", "Medium"),
 ("KNW", IDP, "Records digitisation & archiving", "Paper archives",
  "Scanning with IDP indexing and retention classification.",
  "Paper records", "Retrieval time", "National archives and retention rules.", "Low"),
 ("FIN", ML, "Fraud & error detection in payments / subsidies", "Improper payments",
  "Anomaly detection with investigator review before any action on individuals.",
  "Payment history, eligibility data", "Improper payments prevented", "Human decision; fairness; due process.", "Medium"),
 ("OPS", VIS, "Traffic & mobility analytics", "Congestion data limited",
  "Video / sensor analytics for traffic flow without identifying individuals.",
  "Camera / sensor feeds", "Congestion; incident response", "Privacy by design; remote biometric identification restrictions (EU AI Act Art. 5).", "Medium"),
 ("CUS", GEN, "Complaints & suggestions analysis (Tawasul)", "Themes not visible across entities",
  "GenAI categorisation and theme dashboards for complaints and suggestions.",
  "Complaint records", "Resolution time; recurring themes", "Personal data minimisation.", "Low"),
 ("HR", RPA, "Civil-service HR & payroll transactions", "Manual transactions",
  "Workflow and RPA for routine HR transactions.",
  "HR system", "Processing time", "-", "Low"),
 ("STR", BI, "Open data & statistics publication", "Manual statistics production",
  "Automated data pipelines and dashboards for statistics release.",
  "Administrative data", "Release time", "Disclosure control.", "Low"),
 ("OPS", ML, "Emergency-call prioritisation", "Dispatch prioritisation inconsistent",
  "Decision support for call triage under strict validation; dispatcher decides.",
  "Call records, outcomes", "Response times", "HIGH-RISK: EU AI Act Annex III 5(d) emergency call evaluation and dispatch.", "High"),
],
"RET": [
 ("PRC", ML, "Demand forecasting & replenishment", "Stock-outs and waste",
  "ML forecasts by SKU / store with automated replenishment proposals.",
  "Sales, promotions, calendar data", "Forecast accuracy; availability; waste", "-", "Low"),
 ("MKT", ML, "Dynamic pricing & markdowns", "Prices and markdowns set manually",
  "Price-elasticity models with guardrails and approval of price changes.",
  "Price and sales history, competitor prices", "Margin; sell-through", "Consumer-protection rules; no discriminatory pricing.", "Medium"),
 ("MKT", GEN, "Product content (Arabic / English)", "Slow product listing",
  "GenAI product descriptions and attributes from supplier data; merchandiser review.",
  "Supplier product data, images", "Time to list; content quality", "Accuracy of claims.", "Low"),
 ("CUS", CONV, "Customer service & order tracking", "Repetitive 'where is my order' contacts",
  "Virtual assistant with order and returns integration.",
  "Order / logistics APIs", "Containment; CSAT", "Disclose AI.", "Low"),
 ("MKT", ML, "Personalised recommendations", "Low basket size online",
  "Recommendation engine on browsing and purchase history.",
  "Clickstream, purchase history", "Conversion; basket size", "Consent, profiling transparency (PDPL).", "Medium"),
 ("CUS", RULE, "Returns & refunds", "Manual approval of returns",
  "Rules-based return authorisation with fraud flags.",
  "Order and return history", "Refund time; return fraud", "-", "Low"),
 ("MKT", ML, "Loyalty analytics & segmentation", "Loyalty data unused",
  "Segmentation and propensity models for loyalty campaigns.",
  "Loyalty transactions", "Active members; campaign ROI", "Consent; PDPL.", "Medium"),
 ("OPS", VIS, "Shelf monitoring & planogram compliance", "Gaps found late",
  "Image recognition of shelf gaps and planogram compliance from store photos.",
  "Shelf images", "On-shelf availability", "Avoid capturing shoppers' faces.", "Low"),
 ("OPS", VIS, "Store footfall analytics", "No data on store traffic",
  "Anonymous people-counting and heatmaps.",
  "Sensor / camera feeds", "Conversion; staffing match", "Anonymisation; no biometric identification.", "Medium"),
 ("FIN", IDP, "Supplier orders & invoices", "Paper delivery notes and invoices",
  "IDP of supplier documents with three-way match.",
  "Delivery notes, invoices", "Processing cost", "-", "Low"),
 ("RCL", ML, "Fraud & promotion abuse detection", "Coupon and refund abuse",
  "Anomaly detection on transactions and returns.",
  "Transactions, returns", "Losses prevented", "Human review of account actions.", "Low"),
],
"HOS": [
 ("MKT", ML, "Revenue management & dynamic pricing", "Rates set manually",
  "Demand forecasting and rate recommendations within revenue-manager guardrails.",
  "Booking pace, competitor rates, events", "RevPAR; occupancy", "Transparent pricing.", "Low"),
 ("CUS", CONV, "Guest messaging & concierge (WhatsApp)", "Front desk overloaded",
  "Bilingual guest assistant for requests, bookings and FAQs integrated with PMS.",
  "PMS, service catalogue", "Response time; upsell revenue; guest satisfaction", "Disclose AI; guest data (PDPL).", "Low"),
 ("OPS", RPA, "Reservations & channel updates", "Manual channel updates",
  "Channel-manager integration and RPA for remaining manual steps.",
  "PMS, OTA channels", "Booking errors; time", "-", "Low"),
 ("MKT", GEN, "Review & reputation management", "Reviews unanswered",
  "GenAI-drafted review responses and theme analysis; manager approves.",
  "Online reviews", "Response rate; rating", "Brand tone review.", "Low"),
 ("OPS", ML, "Housekeeping scheduling", "Rooms not ready on time",
  "Optimised housekeeping assignments based on arrivals and departures.",
  "PMS status, staff rosters", "Room-ready time; productivity", "-", "Low"),
 ("PRC", ML, "F&B demand forecasting & waste reduction", "Food waste and stock-outs",
  "Covers forecasting and prep planning.",
  "POS, covers, events", "Food waste; food cost %", "-", "Low"),
 ("MKT", GEN, "Event & MICE proposals", "Proposals slow",
  "GenAI proposal drafting from venue and menu library.",
  "Venue data, past proposals", "Proposal time; conversion", "-", "Low"),
 ("OPS", IDP, "Guest check-in & ID capture", "Queues at check-in",
  "Passport / ID capture with data entry automation and online check-in.",
  "ID documents", "Check-in time", "ID data protection; legal reporting duties.", "Medium"),
 ("AST", ML, "Hotel energy management", "High energy cost",
  "Occupancy-linked HVAC optimisation.",
  "BMS, occupancy data", "kWh per occupied room", "-", "Low"),
 ("MKT", ML, "Personalised upsell offers", "Missed upsell",
  "Propensity-based upgrade and package offers pre-arrival.",
  "Guest history", "Upsell revenue", "Consent; PDPL.", "Medium"),
],
"MFG": [
 ("AST", ML, "Predictive maintenance", "Unplanned downtime",
  "Condition-based models on sensor data triggering work orders (ISO 55000 asset management).",
  "Sensor / SCADA history, failure records", "Unplanned downtime; maintenance cost", "OT security segregation.", "Low"),
 ("OPS", VIS, "Visual quality inspection", "Defects missed by manual inspection",
  "Computer-vision inspection at line speed with operator confirmation of rejects.",
  "Labelled defect images", "Defect escape rate; scrap", "Model drift monitoring.", "Low"),
 ("OPS", ML, "Production scheduling optimisation", "Frequent changeovers and delays",
  "Optimisation of schedules against capacity and due dates.",
  "Orders, routings, capacities", "OTIF; utilisation", "-", "Low"),
 ("AST", ML, "Energy optimisation", "High energy use",
  "ML optimisation of energy-intensive equipment (ISO 50001).",
  "Energy and process data", "Energy per unit", "-", "Low"),
 ("PRC", IDP, "Supplier certificates & quality documents", "Certificates checked manually",
  "IDP extraction and validation of material certificates.",
  "Certificates of analysis / conformity", "Inspection time; non-conformances", "-", "Low"),
 ("KNW", RAG, "Maintenance troubleshooting assistant", "Technicians search manuals",
  "Grounded assistant over manuals, SOPs and past work orders.",
  "Manuals, work orders", "MTTR; first-time fix", "Safety-critical steps verified against SOP.", "Low"),
 ("RCL", VIS, "Health & safety monitoring (PPE)", "Unsafe acts not detected",
  "Video analytics for PPE and exclusion zones with privacy safeguards.",
  "Camera feeds", "Incidents; near-misses", "Worker privacy; no biometric identification; ISO 45001.", "Medium"),
 ("PRC", ML, "Spare-parts & inventory optimisation", "Excess spares, critical stock-outs",
  "Demand and criticality-based inventory optimisation.",
  "Consumption history", "Inventory value; stock-outs", "-", "Low"),
 ("CUS", IDP, "Customer order entry", "Orders from email / PDF keyed manually",
  "IDP of purchase orders into ERP with validation.",
  "Customer POs", "Order-entry time; errors", "-", "Low"),
 ("OPS", ML, "Process yield optimisation", "Variable yield",
  "ML on process parameters to recommend set-points; engineers approve.",
  "Process and quality data", "Yield; scrap", "-", "Low"),
 ("PRC", RPA, "Export documentation", "Documents prepared manually",
  "Automated generation of export documents from ERP data.",
  "Orders, shipping data", "Preparation time; errors", "Customs compliance.", "Low"),
],
"ENR": [
 ("AST", ML, "Asset integrity & corrosion prediction", "Inspection not risk-based",
  "Risk-based inspection supported by ML corrosion models; engineers decide.",
  "Inspection data, process conditions", "Failures; inspection cost", "Process safety - human decision; critical infrastructure.", "Medium"),
 ("AST", VIS, "Drone & visual inspection of assets", "Hazardous manual inspections",
  "Drone imagery with defect detection for engineer review.",
  "Imagery, defect labels", "Inspection time; safety exposure", "Aviation / drone permits.", "Low"),
 ("FIN", RULE, "Meter-reading & billing exceptions", "High billing complaints",
  "Rules and anomaly checks on readings before billing.",
  "Meter readings, billing data", "Billing errors; complaints", "-", "Low"),
 ("OPS", ML, "Load / demand forecasting", "Generation and network planning uncertainty",
  "ML load forecasting from smart-meter and weather data.",
  "Load history, weather", "Forecast accuracy; balancing cost", "Critical infrastructure.", "Medium"),
 ("CUS", RPA, "Outage notifications", "Customers unaware of outages",
  "Automated outage communications linked to the outage system.",
  "Outage system, customer contacts", "Calls during outages", "-", "Low"),
 ("RCL", RULE, "Permit-to-work checks", "Permit errors",
  "Digital permit-to-work with rule-based conflict checks.",
  "Permits, isolation registers", "Permit errors; incidents", "Safety-critical - validated rules.", "Medium"),
 ("KNW", RAG, "Engineering document search", "Engineers search drawings and standards",
  "Grounded assistant over engineering documents and standards.",
  "Drawings, procedures", "Search time", "Document control; latest revision only.", "Low"),
 ("OPS", ML, "Leak & loss detection", "Non-revenue water / gas losses",
  "ML on flow and pressure data to locate leaks.",
  "Flow / pressure data", "Losses; detection time", "-", "Low"),
 ("RCL", BI, "Emissions monitoring & ESG reporting", "Manual ESG data collection",
  "Automated emissions data pipelines (GHG Protocol) and reporting dashboards.",
  "Fuel, energy and process data", "Reporting time; data quality", "Assurance-ready audit trail.", "Low"),
 ("OPS", RAG, "Field technician assistant", "Technicians lack guidance on site",
  "Mobile assistant over procedures and asset history.",
  "Procedures, asset history", "First-time fix", "Safety steps verified.", "Low"),
],
"LOG": [
 ("OPS", ML, "Route optimisation", "Inefficient routes, late deliveries",
  "Optimisation engine with live traffic and delivery windows.",
  "Orders, locations, fleet data", "Cost per drop; on-time delivery", "-", "Low"),
 ("RCL", IDP, "Customs declaration preparation", "Declarations prepared manually",
  "IDP of commercial documents and automated declaration pre-fill; broker submits.",
  "Invoices, packing lists, HS codes", "Preparation time; customs queries", "Customs compliance; HS classification review.", "Low"),
 ("CUS", RPA, "Shipment tracking & updates", "Customers call for status",
  "Automated tracking notifications and self-service status.",
  "Tracking events", "WISMO contacts", "-", "Low"),
 ("OPS", ML, "Warehouse slotting & picking", "Long picking routes",
  "Slotting optimisation and pick-path routing.",
  "Order lines, SKU dimensions", "Picks per hour", "-", "Low"),
 ("FIN", RULE, "Freight invoice audit", "Overbilling undetected",
  "Rules-based freight audit against contracted rates.",
  "Freight invoices, rate cards", "Overcharges recovered", "-", "Low"),
 ("AST", ML, "Fleet predictive maintenance", "Vehicle breakdowns",
  "Telematics-based maintenance prediction.",
  "Telematics, maintenance history", "Breakdowns; maintenance cost", "-", "Low"),
 ("OPS", ML, "Airport / terminal passenger-flow forecasting", "Queues at peaks",
  "Passenger-flow forecasting for staffing and resources.",
  "Flight schedules, historical flows", "Queue time; staffing efficiency", "-", "Low"),
 ("OPS", VIS, "Driver safety monitoring", "Accidents and risky driving",
  "Telematics and in-cab alerts with clear driver policy.",
  "Telematics, camera events", "Incidents; harsh events", "Employee monitoring transparency; no emotion recognition (EU AI Act Art. 5).", "Medium"),
 ("MKT", GEN, "Quote & booking requests", "Quotes prepared manually",
  "GenAI extraction of quote requests and draft quotes from rate engine.",
  "Emails, rate cards", "Quote turnaround; win rate", "-", "Low"),
],
"REC": [
 ("FIN", IDP, "Lease abstraction", "Lease terms extracted by hand",
  "IDP / GenAI abstraction of key lease terms into the property system with review.",
  "Lease documents", "Abstraction time; missed escalations", "-", "Low"),
 ("CUS", CONV, "Tenant service requests", "Requests by phone and email",
  "Tenant app / virtual assistant with automated work-order creation.",
  "Request history", "Response time; tenant satisfaction", "-", "Low"),
 ("FIN", RPA, "Rent collection & reminders", "Late rent payments",
  "Automated invoicing, reminders and reconciliation.",
  "Lease and payment data", "Collection rate; DSO", "-", "Low"),
 ("OPS", ML, "Property valuation support", "Valuations slow and inconsistent",
  "Automated valuation model supporting (not replacing) certified valuers.",
  "Transaction and property data", "Valuation time; variance", "RERA / valuer standards; human valuer accountable.", "Medium"),
 ("OPS", VIS, "Construction progress monitoring", "Progress reported subjectively",
  "Drone / photo-based progress tracking against schedule.",
  "Site imagery, schedule", "Schedule variance", "-", "Low"),
 ("PRC", GEN, "Tender & BOQ analysis", "Bid comparison slow",
  "GenAI comparison of BOQs and tender submissions; QS reviews.",
  "BOQs, tenders", "Evaluation time", "Fairness; confidentiality.", "Low"),
 ("RCL", VIS, "Site safety monitoring", "Unsafe acts on site",
  "Video analytics for PPE and exclusion zones.",
  "Camera feeds", "Incidents", "Worker privacy; no biometric identification.", "Medium"),
],
"EDU": [
 ("CUS", CONV, "Student enquiries & admissions support", "Admissions office overloaded",
  "Virtual assistant for admissions and student-service questions.",
  "FAQs, programme information", "Response time; enquiries handled", "Disclose AI; minors' data.", "Low"),
 ("OPS", IDP, "Admission document processing", "Documents verified manually",
  "IDP of transcripts and certificates; admissions staff decide.",
  "Applications, transcripts", "Processing time", "If AI influences admission decisions: HIGH-RISK (EU AI Act Annex III 3(a)); human decision.", "Medium"),
 ("OPS", GEN, "Assessment & marking support", "Marking workload",
  "AI-suggested feedback and marking for teacher moderation only.",
  "Rubrics, sample marked work", "Marking time; feedback quality", "HIGH-RISK: EU AI Act Annex III 3(b) evaluating learning outcomes; teacher decides.", "High"),
 ("OPS", GEN, "Course content & quiz generation", "Content development time",
  "GenAI-assisted course materials from approved sources; faculty review.",
  "Curriculum, source materials", "Development time", "BQA quality standards; copyright.", "Low"),
 ("OPS", ML, "Student at-risk early warning", "Drop-outs identified late",
  "Early-warning indicators for advisors with supportive (not punitive) interventions.",
  "Attendance, grades, LMS activity", "Retention; intervention timeliness", "HIGH-RISK: EU AI Act Annex III (3); fairness; minors.", "High"),
 ("OPS", ML, "Timetabling optimisation", "Timetables built manually",
  "Constraint-based timetable optimisation.",
  "Courses, rooms, staff constraints", "Clashes; room utilisation", "-", "Low"),
 ("KNW", RAG, "Library & research assistant", "Students struggle to find sources",
  "Research assistant over library holdings with citations and academic-integrity guidance.",
  "Library catalogue, licensed databases", "Usage; satisfaction", "Academic integrity policy.", "Low"),
],
"PRO": [
 ("OPS", ML, "Audit - journal-entry testing (full population)", "Sample-based testing of large ledgers",
  "Full-population JE analytics with rules and ML anomaly scoring; auditor investigates and concludes.",
  "Client GL / JE extracts", "Coverage; exceptions investigated; audit hours", "ISA 240 / 330; documentation in working papers; client-data confidentiality.", "Medium"),
 ("OPS", GEN, "Audit - working papers & memo drafting", "Senior time spent drafting standard documentation",
  "GenAI drafting within methodology templates in an approved environment; reviewer sign-off.",
  "Methodology templates, engagement data", "Drafting time; review points", "ISQM 1; human review; client confidentiality.", "Medium"),
 ("OPS", IDP, "Audit - bank & external confirmations", "Confirmations read and keyed manually",
  "IDP of confirmation responses with automatic agreement to records.",
  "Confirmation responses, client balances", "Processing time; exceptions", "ISA 505 evidence requirements.", "Low"),
 ("OPS", RAG, "Tax research & technical Q&A", "Research across NBR guidance, laws and prior advice",
  "Grounded tax assistant over Bahrain / GCC tax law, NBR guidance and approved internal positions with citations.",
  "Tax laws, NBR guidance, approved positions", "Research time; quality review points", "Partner review of advice; verify citations.", "Low"),
 ("OPS", RPA, "Tax - VAT / tax return data preparation", "Client data collated manually",
  "Automated extraction, mapping and validation of client data into returns.",
  "Client ledgers, VAT codes", "Preparation time; errors", "Maker-checker; client sign-off.", "Low"),
 ("OPS", ML, "Predictive tax scenario modelling", "Tax outcomes analysed after decisions",
  "Scenario models of tax outcomes for planning decisions (e.g., Pillar Two, CIT).",
  "Client financial data, tax rules", "Advisory hours; scenario turnaround", "Assumptions documented; partner review.", "Medium"),
 ("OPS", GEN, "Advisory - due-diligence data-room review", "Large data rooms reviewed by hand",
  "GenAI review of data-room documents against DD checklists with red-flag summaries.",
  "Data-room documents, DD checklist", "Review time; issues identified", "Confidentiality; NDA terms; verify findings.", "Medium"),
 ("RCL", RULE, "Client acceptance & independence checks", "Checks collated by email and spreadsheets",
  "Workflow with rules-based independence and conflict checks against the client database.",
  "Client and engagement database", "Acceptance cycle time; breaches", "IESBA Code; ISQM 1.", "Low"),
 ("FIN", RPA, "Timesheets, WIP & billing", "Chasing timesheets; manual billing narratives",
  "Automated timesheet reminders, WIP reports and draft billing narratives.",
  "Timesheets, engagement codes", "Lock-up days; billing time", "-", "Low"),
 ("OPS", AGT, "Engagement workflow coordination", "Status chased across teams",
  "Supervised agent tracking requests-for-information and status across tools; staff approve client communication.",
  "Engagement tools, RFI lists", "Status-chasing hours; RFI turnaround", "Agent least privilege; client data boundaries.", "Medium"),
 ("OPS", ML, "Financial statements preparation (GT AI FS tool - in preparation)", "Mapping trial balances and drafting notes manually",
  "AI-assisted TB mapping and notes drafting with mandatory accountant review (GT AI-powered Financial Statements tool - in preparation).",
  "Trial balances, prior FS, templates", "Preparation time; review points", "IFRS; IESBA independence for audit clients; professional sign-off.", "Medium"),
 ("RCL", GEN, "Client BCP & business impact analysis (GT AI BCP tool - in preparation)", "Generic, outdated plans; slow BIA workshops",
  "AI-assisted BIA and ISO 22301-aligned plan drafting (GT AI-powered BCP tool - in preparation).",
  "Client process data, dependencies", "Delivery time; plan quality", "Client validation of plans; confidentiality.", "Medium"),
 ("OPS", RPA, "Assessment & maturity report production", "Reports built manually per client",
  "Questionnaire-driven automated report generation with professional review (as for the GT AI Readiness Assessment).",
  "Questionnaire responses, scoring model", "Report turnaround", "Quality review before issue.", "Low"),
 ("OPS", GEN, "Governance 'tone at the top' analysis", "Governance signals in filings missed",
  "NLP analysis of management commentary and filings for tone and sentiment shifts to flag governance risk early.",
  "Annual reports, filings, minutes", "Early-warning flags", "Professional judgement; avoid over-reliance on sentiment scores.", "Medium"),
 ("KNW", RAG, "Methodology & knowledge Q&A", "Staff search across manuals and past work",
  "Grounded assistant over firm methodologies and sanitised precedents.",
  "Methodologies, sanitised precedents", "Search time; reuse", "Client confidentiality in precedents.", "Low"),
],
}

LIBRARY = []   # (id, sector name, function name, nature idx, process, pain, recommendation, data, kpis, notes, floor)
for code in SECTOR_ORDER:
    for i, (fn, nat, proc, pain, rec, data, kpi, notes, floor) in enumerate(_L[code], 1):
        LIBRARY.append((f"{code}-{i:02d}", SECTORS[code], FUNCTIONS[fn][0], nat, proc, pain, rec, data, kpi, notes, floor))

# Sector profiles (value data: QuantumBlack & PwC analysis, 2030 predictions, as cited in GT Bahrain 'Introduction to AI', 2026)
SECTOR_PROFILES = [
    # sector, GDP uplift by 2030 (where available), automation & AI potential, value pools, regulators / key rules
    ("Banking & payments", "$2.1T  |  10.0%", "Very high",
     "Onboarding & KYC, financial-crime alert triage, fraud, credit, customer service, regulatory reporting",
     "CBB Rulebook (e.g., FC financial crime, OM operational risk, BC business conduct); PDPL; FATF; EU AI Act Annex III 5(b) credit scoring; model risk (SR 11-7 principles)"),
    ("Insurance", "$2.1T  |  10.0% (financial services)", "Very high",
     "Claims intake & settlement, claims fraud, underwriting intake, policy servicing",
     "CBB Rulebook (insurance); PDPL (health data sensitive); EU AI Act Annex III 5(c) life & health pricing"),
    ("Capital markets & wealth", "$2.1T  |  10.0% (financial services)", "High",
     "Reconciliations, surveillance, research, client reporting",
     "CBB capital-market rules; market-abuse rules; FATF"),
    ("Healthcare", "$5.1T  |  20.7%", "Very high",
     "Revenue cycle, scheduling, documentation, coding, imaging and early warning (regulated)",
     "NHRA (facility, professional and medical-device rules); PDPL (health data sensitive); EU MDR / AI Act Annex I for medical-device AI; Annex III 5(d) triage"),
    ("Telecommunications", "$305B  |  12.4% (technology, communications & entertainment)", "Very high",
     "Network operations (AIOps), churn, care automation, fraud, revenue assurance",
     "TRA (consumer protection, QoS, licensing); PDPL; critical-infrastructure resilience"),
    ("Government & public sector", "Not sized separately in the 2030 analysis - value from faster citizen services, application processing and translation (iGA AI Policy 2025)", "High",
     "Citizen services, application processing, translation, records, inspections",
     "iGA General Policy for the Use of AI (2025); PDPL; EU AI Act Annex III 5(a) public assistance; transparency and appeal rights"),
    ("Retail & e-commerce", "$2.0T  |  14.8%", "High",
     "Demand forecasting, pricing, personalisation, content, service",
     "PDPL (consent, profiling); consumer-protection rules"),
    ("Hospitality & tourism", "$2.0T  |  14.8% (retail & consumer)", "High",
     "Revenue management, guest messaging, reputation, F&B waste",
     "PDPL (guest data); tourism licensing rules"),
    ("Manufacturing & industrial", "$4.0T  |  11.9%", "High",
     "Predictive maintenance, quality inspection, scheduling, energy",
     "OT security (IEC 62443); ISO 45001 / 55000 / 50001"),
    ("Oil, gas, energy & utilities", "$1.7T  |  12.0%", "High",
     "Asset integrity, inspection, load forecasting, leak detection, ESG reporting",
     "Critical infrastructure; process safety; EU AI Act Annex III (2) critical-infrastructure safety components"),
    ("Logistics, aviation & transport", "$569B  |  10.3%", "High",
     "Routing, warehouse optimisation, customs documents, fleet maintenance",
     "Customs rules; driver-monitoring privacy; aviation safety rules"),
    ("Real estate & construction", "Not sized separately in the 2030 analysis - value from lease administration, tenant service and construction productivity", "Medium",
     "Lease abstraction, tenant service, rent collection, progress monitoring",
     "RERA; PDPL; site-safety rules"),
    ("Education", "Not sized separately in the 2030 analysis - value from student services, content development and timetabling", "Medium",
     "Student service, content, timetabling - assessment and admissions are high-risk",
     "BQA; PDPL (minors); EU AI Act Annex III (3) education"),
    ("Professional services", "Not sized separately in the 2030 analysis - value from audit, tax and advisory delivery (e.g., full-population auditing, predictive tax modelling, DD review)", "High",
     "Audit analytics, drafting, tax research, DD review, practice operations",
     "ISQM 1; IESBA Code; ISAs; client confidentiality; PDPL"),
]
