# -*- coding: utf-8 -*-
"""Content for the AI RCM v2.0 (2026 update).

EXISTING  : enrichment metadata for the 44 original controls (keyed by Control ID)
NEW       : 28 new controls identified through the gap analysis
DOMAINS   : domain order (existing domains + one new domain)
"""

DOMAINS = [
    "Governance & Leadership",
    "Risk Management",
    "Regulatory Operations",
    "System, Data and Model Lifecycle",
    "Security",
    "Safe Responsible AI",
    "Privacy",
    "Assurance and Audit",
    "Operational Monitoring",
    "Third Party & Supply Chain",
    "Transparency & Communication",
    "Incident Management",
    "Protection from AI-Enabled Threats",
]

# id: (iso27001_2022, additional_refs, bahrain_gcc_refs, ready7, applicability, control_type, frequency, notes)
EXISTING = {
    "GL-1": ("Cl. 5.1, 5.2, 9.3; A.5.1, A.5.2, A.5.4",
             "ISO/IEC 38507:2022 cl.4-6 (governance implications of AI)\nISO/IEC 23894:2023 cl.5.2\nOECD AI Principle 1.5 (Accountability)\nIEEE 7000-2021",
             "iGA General Policy for the Use of AI v1.0 (2025) - Pillar 1\nGCC Guiding Manual on the Ethics of AI Use (Accountability)\nCBB Rulebook HC Module (board responsibility) - CBB licensees",
             "1.1", "Both", "Directive", "Annual policy review; quarterly executive AI risk review",
             "EU AI Act reference '4.1' corrected: Art. 4 is AI literacy (now mapped to GL-4). Executive accountability maps to Art. 17(1)(m) and Art. 26."),
    "GL-2": ("Cl. 5.3, 7.1-7.3; A.5.2, A.5.3, A.6.3",
             "ISO/IEC 38507:2022\nNIST AI RMF Govern 2.1, 2.2\nEU AI Act Art. 26(2) (competent, trained oversight persons)",
             "iGA General Policy for the Use of AI v1.0 - roles of government entities\nCBB Rulebook HC Module (approved persons / governance)",
             "1.1, 3.4", "Both", "Directive", "Annual",
             "EU AI Act Art. 22 applies only to non-EU providers appointing an EU authorised representative - retain only where relevant."),
    "GL-3": ("Cl. 4.1-4.4, 6.2",
             "OECD AI Principle 1.1 (Inclusive growth & well-being)\nNIST AI 600-1 GV-1.1\nUNESCO Recommendation on the Ethics of AI (2021) Policy Area 1",
             "Bahrain Economic Vision 2030\niGA General Policy for the Use of AI - Pillar 2 (Adoption)\nUNESCO AI Readiness Assessment (RAM) Report - Bahrain (Nov 2025)",
             "1.1, 1.3", "Both", "Directive", "Annual (strategy cycle)", ""),
    "RM-1": ("Cl. 6.1, 8.2, 8.3; A.5.1",
             "ISO/IEC 23894:2023 cl.5-6 (AI risk management)\nISO 31000:2018\nISO/IEC 42001 cl.6.1.2 (AI risk assessment)\nNIST AI 600-1 (12 GAI risk categories)",
             "CBB Rulebook RM Module (risk management) - CBB licensees\nSDAIA AI Ethics Principles (risk-based approach) - KSA operations",
             "2.4", "Both", "Directive", "Annual framework review",
             "Risk appetite and KRIs now covered explicitly by new control RM-6."),
    "RM-2": ("Cl. 6.1.2; A.5.7",
             "ISO/IEC 42005:2025 (AI system impact assessment)\nEU AI Act Art. 27 (Fundamental Rights Impact Assessment)\nCouncil of Europe HUDERIA methodology (2024)\nNSW AI Assessment Framework (AIAF)",
             "Bahrain PDPL (Law No. 30 of 2018) - processing risk\nGCC Guiding Manual on the Ethics of AI Use",
             "2.4", "Both", "Preventive", "Per use case, before deployment and on material change", ""),
    "RM-3": ("Cl. 6.1.3, 8.1-8.3",
             "ISO/IEC 23894:2023 cl.6.5 (risk treatment)\nEU AI Act Art. 17 (QMS)\nNIST AI 600-1 MG-2",
             "CBB Rulebook RM Module",
             "2.4", "Both", "Preventive", "Per risk assessment cycle", ""),
    "RM-4": ("Cl. 6.1.3, 9.1; A.5.7",
             "ISO/IEC 23894:2023 cl.6.6 (monitoring & review)\nNIST AI 600-1 MS-2, MG-3\nMIT AI Risk Repository (emerging-risk taxonomy)",
             "CBB Rulebook RM Module",
             "2.4, 4.4", "Both", "Detective", "Continuous; quarterly reporting", ""),
    "RO-1": ("A.5.31, A.5.32, A.5.33, A.5.34, A.5.36",
             "EU AI Act Art. 5 (prohibitions - applicable since 2 Feb 2025), Art. 6 & Annex III, Art. 49 (EU database registration)\nKorea AI Basic Act (effective 22 Jan 2026)\nColorado AI Act SB 24-205\nCouncil of Europe Framework Convention on AI (CETS 225)",
             "Bahrain draft AI Regulation Law (Shura-approved Apr 2024; pending)\nBahrain PDPL (Law No. 30 of 2018)\nLaw No. 60 of 2014 on Information Technology Crimes\niGA General Policy for the Use of AI - Pillar 1",
             "2.2", "Both", "Directive", "Continuous horizon scanning; annual compliance attestation",
             "Multi-jurisdiction obligation tracking now explicit in new control RO-5."),
    "RO-2": ("A.5.5, A.5.24, A.5.26",
             "EU AI Act Art. 26(11) (inform persons subject to high-risk AI decisions)\nGDPR Art. 13-14, 22\nISO/IEC 42001 A.8.2-A.8.5",
             "Bahrain PDPL - notice to data subjects\nGCC Guiding Manual on the Ethics of AI Use (Transparency)",
             "1.4, 2.2", "Both", "Directive", "Per system; on significant change", ""),
    "RO-3": ("Cl. 7.5; A.5.31, A.5.33",
             "EU AI Act Art. 18 (10-year retention - providers), Art. 26(6) (log retention >= 6 months - deployers)\nISO/IEC 42001 cl.7.5",
             "Bahrain PDPL - processing records\nCBB Rulebook record-keeping requirements (licensees)",
             "2.2", "Both", "Directive", "Continuous; annual retention review", ""),
    "RO-4": ("Cl. 9.1; A.5.7, A.8.16",
             "EU AI Act Art. 72 (post-market monitoring plan)\nISO/IEC 42001 cl.9.1\nNIST AI 600-1 MS-2",
             "CBB supervisory reporting (licensees)",
             "4.4", "Provider", "Detective", "Continuous; periodic PMM report", ""),
    "LC-1": ("A.5.12, A.5.33, A.8.11, A.8.33",
             "ISO/IEC 5259-1 to -5 (data quality for analytics & ML)\nISO/IEC 8183:2023 (data life cycle framework)\nISO/IEC TR 24027:2021 (bias in AI systems)\nNIST AI 600-1 (data provenance)",
             "Bahrain Open Data Policy (iGA)\nBahrain PDPL - data quality principle",
             "5.1, 5.4", "Both", "Preventive", "Per dataset; before training/fine-tuning and on refresh", ""),
    "LC-2": ("A.5.8, A.8.25, A.8.26, A.8.27, A.8.29",
             "ISO/IEC 5338:2023 (AI system life cycle processes)\nISO/IEC 22989:2022 cl.6\nISO/IEC 42001 A.6",
             "iGA government digital standards (public-sector systems)",
             "4.1, 6.3", "Provider", "Preventive", "Per development project", ""),
    "LC-3": ("A.5.9, A.5.10, A.8.6",
             "ISO/IEC 42001 A.4.2-A.4.6\nISO/IEC 5338:2023",
             "",
             "2.5, 4.5", "Both", "Directive", "Quarterly inventory reconciliation",
             "AI system register (use-case level) now explicit in new control GL-8."),
    "LC-4": ("Cl. 7.5; A.5.37",
             "EU AI Act Annex IV (technical documentation content)\nISO/IEC 42001 A.6.2.7\nModel / system cards (industry practice)",
             "",
             "2.2, 6.5", "Provider", "Directive", "Per release", ""),
    "LC-5": ("A.8.9, A.8.32, A.8.4",
             "ISO/IEC 5338:2023 (change management)\nEU AI Act Art. 3(23) 'substantial modification' & Art. 43(4)\nNIST AI RMF Manage 2.4",
             "",
             "6.3", "Both", "Preventive", "Per change", ""),
    "SE-1": ("A.5.1, A.5.2, A.5.7, A.5.29, A.5.30, A.5.35, A.5.36, A.8.14",
             "NIST CSF 2.0 (GV, ID functions)\nETSI EN 304 223 / TS 104 223 (baseline cyber security requirements for AI)\nUK AI Cyber Security Code of Practice (2025)\nISO/IEC 27090 (AI security guidance - draft)",
             "Bahrain National Cyber Security Center (NCSC) standards\nCBB Rulebook OM Module - cyber security risk management (licensees)\nKSA NCA ECC-2:2024 (KSA operations)",
             "4.1, 6.2", "Both", "Directive", "Annual", "ISO/IEC 27001 references in the original RCM mix 2013 and 2022 Annex A numbering - remapped in the ISO/IEC 27001:2022 column."),
    "SE-2": ("A.5.15, A.5.16, A.5.17, A.5.18, A.8.2, A.8.3, A.8.5",
             "NIST SP 800-207 (Zero Trust)\nOWASP LLM06:2025 Excessive Agency\nOWASP Top 10 for Agentic Applications (identity & privilege abuse)\nETSI EN 304 223",
             "NCSC standards\nCBB Rulebook OM Module (access control)",
             "6.1, 4.3", "Both", "Preventive", "Quarterly access reviews; continuous enforcement", "Non-human (agent) identities addressed in new control LC-8."),
    "SE-3": ("A.8.8, A.8.25, A.8.26, A.8.27, A.8.28, A.8.29, A.8.31, A.8.32",
             "OWASP Top 10 for LLM Applications 2025\nMITRE ATLAS\nNIST SP 800-218A (SSDF community profile for GenAI, 2024)\nNIST AI 100-2 E2025 (adversarial ML taxonomy)",
             "NCSC standards",
             "6.3", "Provider", "Preventive", "Per release; continuous in CI/CD", "AI-specific attack coverage expanded in new control SE-6."),
    "SE-4": ("A.5.12, A.5.13, A.5.33, A.8.10, A.8.11, A.8.12, A.8.13, A.8.24",
             "CISA/NSA/FBI 'AI Data Security' guidance (May 2025)\nOWASP LLM02:2025 Sensitive Information Disclosure",
             "Bahrain PDPL - security of processing\nLegislative Decree No. 56 of 2018 (cloud computing services to foreign parties)",
             "5.1, 5.3, 6.2", "Both", "Preventive", "Continuous", ""),
    "SE-5": ("A.8.15, A.8.16, A.8.20, A.8.21, A.8.22, A.8.23",
             "NIST SP 800-207 (Zero Trust)\nETSI EN 304 223 (secure infrastructure)",
             "NCSC standards",
             "4.3", "Both", "Preventive", "Continuous; annual architecture review", ""),
    "RS-1": ("No direct equivalent (AI-specific)",
             "EU AI Act Art. 26(2)\nISO/IEC 22989:2022 (human oversight concepts)\nNIST AI 600-1 (human-AI configuration)",
             "GCC Guiding Manual on the Ethics of AI Use (Human oversight)\nSDAIA AI Ethics Principles (Humanity)",
             "5.2", "Both", "Preventive", "Per decision / per workflow", ""),
    "RS-2": ("A.5.8",
             "EU AI Act Art. 5(1)(a)-(b) (manipulation, exploitation of vulnerabilities)\nNIST AI 600-1 (dangerous / violent / hateful content)\nISO/IEC TR 24368:2022",
             "GCC Guiding Manual on the Ethics of AI Use (Safety)",
             "2.3", "Both", "Preventive", "Per use case; continuous monitoring", ""),
    "RS-3": ("A.5.29, A.5.30, A.8.14",
             "ISO/IEC TR 24029-1:2021 & ISO/IEC 24029-2:2023 (robustness of neural networks)\nNIST AI 100-2 E2025\nEU AI Act Art. 15(4)",
             "",
             "6.4", "Provider", "Preventive", "Pre-deployment; periodic", ""),
    "RS-4": ("No direct equivalent (AI-specific)",
             "EU AI Act Art. 13 (instructions for use), Art. 86 (right to explanation)\nGDPR Art. 22(3)\nNIST IR 8312 (Four principles of explainable AI)",
             "GCC Guiding Manual on the Ethics of AI Use (Explainability)",
             "1.4, 2.3", "Both", "Directive", "Per system", "EU AI Act references 50.2-50.5 relate to GenAI transparency; explainability primarily maps to Art. 13 and Art. 86."),
    "RS-5": ("No direct equivalent (AI-specific)",
             "ISO/IEC TR 24027:2021 (bias in AI systems)\nNIST SP 1270 (identifying and managing bias)\nIEEE 7003-2024 (algorithmic bias considerations)\nEU AI Act Art. 10(2)(f)-(g), 10(5)",
             "GCC Guiding Manual on the Ethics of AI Use (Fairness)\nSDAIA AI Ethics Principles (Fairness)",
             "2.3, 3.2", "Both", "Detective", "Pre-deployment; at least annually in operation", "EU AI Act Art. 5(1) is the prohibitions list; bias data-governance duties sit in Art. 10(2)(f)-(g) and 10(5)."),
    "RS-6": ("No direct equivalent (AI-specific)",
             "ISO/IEC TS 4213:2022 (ML classification performance)\nISO/IEC 25059:2023 (quality model for AI systems)\nEU AI Act Art. 15(3)",
             "",
             "4.4", "Provider", "Detective", "Per release; monitored continuously", ""),
    "PR-1": ("A.5.34, A.8.10, A.8.11, A.8.12",
             "ISO/IEC 27701:2025 (standalone PIMS - remap clause references at next review)\nISO/IEC 29134 (PIA)\nGDPR Art. 25, 35",
             "Bahrain PDPL (Law No. 30 of 2018) - Personal Data Protection Authority\nKSA PDPL (KSA operations)\nUAE Federal Decree-Law 45/2021 (UAE operations)",
             "5.5", "Both", "Preventive", "Per system; annual review", "ISO/IEC 27701 clause numbers reference the 2019 edition."),
    "PR-2": ("A.5.34, A.8.10",
             "GDPR Art. 5, 6, 9\nISO/IEC 29100",
             "Bahrain PDPL - lawful processing, sensitive data, data-subject rights",
             "5.1, 5.5", "Both", "Preventive", "Continuous", ""),
    "PR-3": ("A.5.24, A.5.34, A.5.35",
             "GDPR Art. 33-34\nISO/IEC 27701:2025",
             "Bahrain PDPL - supervision by the Personal Data Protection Authority",
             "5.5", "Both", "Detective", "Annual privacy audit", ""),
    "PR-4": ("A.8.10, A.8.11, A.8.24",
             "ISO/IEC 20889:2018 (de-identification techniques)\nISO/IEC 27559:2022 (de-identification framework)\nNIST SP 800-226 (differential privacy guidelines, 2025)",
             "Bahrain PDPL",
             "5.5", "Both", "Preventive", "Per system; annual effectiveness test", ""),
    "AA-1": ("Cl. 9.2; A.5.35, A.5.36",
             "ISO/IEC 42001 cl.9.2\nISO/IEC 42006:2025 (requirements for AIMS audit bodies)\nIIA AI Auditing Framework",
             "CBB Rulebook - internal audit requirements (licensees)",
             "2.2", "Both", "Detective", "Annual internal audit plan", ""),
    "AA-2": ("Cl. 9.3, 10.1, 10.2; A.5.35",
             "ISO/IEC 42006:2025\nISO/IEC 17021-1\nEU AI Act Art. 43 & Annex VI/VII",
             "",
             "1.4", "Both", "Detective", "Per certification cycle (3-year with annual surveillance)", ""),
    "AA-3": ("A.5.36, A.8.8, A.8.29",
             "OWASP GenAI Red Teaming Guide (2025)\nMITRE ATLAS\nNIST AI 100-2 E2025\nEU AI Act Art. 55(1)(a) (adversarial testing - GPAI with systemic risk)",
             "NCSC standards",
             "6.4", "Both", "Detective", "Pre-deployment; at least annually", ""),
    "OM-1": ("A.8.6, A.8.16",
             "NIST AI 600-1 MS-2\nISO/IEC 42001 A.6.2.6\nISO/IEC 5338:2023 (operation & monitoring stage)",
             "",
             "4.4", "Both", "Detective", "Continuous", ""),
    "OM-2": ("A.8.15, A.8.17, A.8.34",
             "EU AI Act Art. 26(6) (deployer log retention >= 6 months)\nISO/IEC 27002:2022 8.15",
             "CBB Rulebook - record retention (licensees)",
             "6.5", "Both", "Detective", "Continuous", ""),
    "OM-3": ("Cl. 10.1, 10.2; A.5.27",
             "ISO/IEC 42001 cl.10\nISO/IEC 5338:2023",
             "",
             "1.3", "Both", "Corrective", "Quarterly", ""),
    "TP-1": ("A.5.19, A.5.20, A.5.23",
             "EU AI Act Art. 25(4) (written agreements with suppliers of high-risk components)\nEU Model Contractual AI Clauses (MCC-AI, 2025 update)",
             "CBB Rulebook OM Module - outsourcing requirements (licensees)",
             "2.4", "Both", "Directive", "Per contract", "Contractual AI clauses expanded in new control TP-3."),
    "TP-2": ("A.5.19, A.5.20, A.5.21, A.5.22, A.5.23",
             "ISO/IEC 42001 A.10.3 (suppliers)\nNIST AI RMF Govern 6.1-6.2\nISO/IEC 27036 (supplier relationships)",
             "CBB Rulebook OM Module - outsourcing (licensees)",
             "2.4, 6.2", "Both", "Detective", "Onboarding; annual re-assessment", ""),
    "CO-1": ("Cl. 7.4",
             "EU AI Act Art. 50 (transparency obligations - apply from 2 Aug 2026)\nC2PA Content Credentials\nNIST AI 600-1 (information integrity)",
             "GCC Guiding Manual on the Ethics of AI Use (Transparency)",
             "1.4", "Both", "Directive", "Per system", ""),
    "CO-2": ("Cl. 4.2, 7.4",
             "ISO/IEC 42001 A.8.3\nNIST AI RMF Govern 5.1\nOECD AI Principle 1.3",
             "iGA General Policy for the Use of AI - Pillar 4 (Cooperation)",
             "1.4", "Both", "Directive", "Semi-annual", "EU AI Act reference '4.1' (AI literacy) is not a stakeholder-engagement obligation - relevant articles are 26(7) and 26(11)."),
    "IM-1": ("A.5.24, A.5.25, A.5.26, A.6.8",
             "OECD AI Incidents Monitor common reporting framework (2025)\nNIST AI 600-1 MG-4.3\nAI Incident Database (AIID)",
             "NCSC incident reporting\nCBB Rulebook OM Module - cyber incident reporting (licensees)",
             "7.4", "Both", "Corrective", "Continuous", ""),
    "IM-2": ("A.5.5, A.5.24, A.5.26, A.6.8",
             "EU AI Act Art. 73 (serious incidents: 15 days; 10 days for death; 2 days for widespread / critical-infrastructure incidents)\nGDPR Art. 33-34",
             "Bahrain PDPL - notification to the PDP Authority where required\nCBB Rulebook - incident notification (licensees)",
             "7.4", "Both", "Corrective", "Per incident", ""),
    "IM-3": ("A.5.27, A.5.28",
             "ISO/IEC 42001 cl.10.2\nNIST AI RMF Manage 4.3",
             "",
             "7.4", "Both", "Corrective", "Per incident; quarterly trend review", ""),
}


def _n(items):
    return "\n".join(f"{i}. {t}" for i, t in enumerate(items, 1))


# Each: domain, id, topic, statement, refs, activities[], evidence[], tests[], iso27001_2022, add_refs, gcc, ready7, applicability, type, freq, rationale
NEW = [
    # ---------------------------------------------------------------- Governance & Leadership
    dict(domain="Governance & Leadership", id="GL-4", topic="AI Literacy & Competence",
         statement="The organisation shall take measures to ensure a sufficient level of AI literacy among all staff and other persons operating or using AI systems on its behalf, taking into account their technical knowledge, experience, education, role and the context in which AI systems are used.\nRole-based competence requirements shall be defined for AI developers, operators, human-oversight personnel, risk and control functions, and leadership, and competence shall be maintained as AI capabilities and risks evolve.",
         refs="ISO42001:7.2 7.3 A.4.6\nEU AI ACT:4 26.2\nNIST AI RMF:Govern 2.2\nOECD:Principle 2.4",
         activities=["Define an AI literacy baseline (safe use, limitations, hallucinations, data handling, bias, escalation) mandatory for all staff and contractors using AI",
                     "Define role-based competence profiles for AI developers, human-oversight personnel, risk/compliance, security and executives",
                     "Deliver and track training (e-learning, scenario-based labs) with completion before AI tool access is granted",
                     "Refresh content at least annually and upon introduction of new AI capabilities (e.g., agents) or material regulatory change",
                     "Measure effectiveness through assessments, phishing/deepfake simulations and incident trend analysis"],
         evidence=["AI literacy policy / training standard and role-based competence matrix",
                   "Training content, curricula and version history",
                   "Learning-management-system completion records mapped to AI tool access lists",
                   "Assessment results and effectiveness metrics reported to governance forum"],
         tests=["Obtain the competence matrix and verify coverage of all AI-related roles",
                "Select a sample of AI tool users and confirm training was completed before access was provisioned",
                "Verify human-oversight personnel for high-risk systems completed role-specific training (EU AI Act Art. 26(2))",
                "Confirm training content was refreshed within the last 12 months",
                "Pass criterion: >= 95% completion for in-scope users and 100% for oversight roles; exceptions tracked with corrective actions"],
         iso="Cl. 7.2, 7.3; A.6.3", add="EU AI Act Art. 4 (applicable since 2 Feb 2025)\nUNESCO AI Competency Frameworks (2024)",
         gcc="iGA General Policy for the Use of AI - Pillar 3 (Awareness & Education)\nBahrain AI Academy initiatives",
         r7="3.1, 3.2, 3.3, 3.4", app="Both", typ="Preventive", freq="Onboarding; annual refresher",
         why="EU AI Act Art. 4 AI-literacy obligation has applied since 2 Feb 2025 and was not represented (the original mapping of '4.1' to GL-1/CO-2 was misplaced). AI Ready7 Pillar 3 has no corresponding RCM control."),
    dict(domain="Governance & Leadership", id="GL-5", topic="AI Acceptable Use & Shadow AI Management",
         statement="The organisation shall establish, communicate and enforce an AI acceptable use policy defining approved AI tools, permitted and prohibited use cases, data that may and may not be entered into AI systems, output verification requirements and disclosure expectations.\nThe organisation shall implement technical and procedural measures to detect unsanctioned (shadow) AI use and provide a governed pathway for bringing valuable use cases into the approved portfolio.",
         refs="ISO42001:A.2.2 A.9.2 A.9.3\nEU AI ACT:5 26.1\nNIST AI RMF:Govern 1.2 Govern 1.6\nSOC2:CC1.4 CC2.2",
         activities=["Publish an AI acceptable use policy covering approved tools, data restrictions (e.g., no confidential/personal data in public GenAI), output verification and attribution",
                     "Maintain an approved AI tools catalogue with risk rating and permitted data classifications",
                     "Obtain staff acknowledgement of the policy annually",
                     "Deploy detection for unsanctioned AI services (CASB / secure web gateway / DLP / SaaS discovery) and review findings monthly",
                     "Operate an intake route that converts discovered shadow-AI use into assessed, approved or blocked use cases"],
         evidence=["Approved AI acceptable use policy and approved-tools catalogue",
                   "Staff acknowledgement records",
                   "Shadow-AI discovery reports and resulting actions",
                   "Records of block/allow decisions and exceptions"],
         tests=["Inspect the policy for coverage of data restrictions, prohibited uses and output verification",
                "Sample users and confirm policy acknowledgement",
                "Review latest shadow-AI discovery report and trace a sample of findings to remediation or approval",
                "Attempt access to a non-approved GenAI service from a managed device to validate enforcement",
                "Pass criterion: policy approved and current; discovery performed monthly; all high-risk findings actioned within defined SLA"],
         iso="A.5.10, A.5.23, A.8.12, A.8.23", add="NSW AIAF - Acceptable Use Policy precedence for public GenAI tools\nOWASP LLM02:2025 (sensitive information disclosure)",
         gcc="iGA General Policy for the Use of AI (government entities)\nBahrain PDPL - personal data restrictions",
         r7="1.2, 2.1", app="Deployer", typ="Preventive", freq="Annual policy review; monthly discovery",
         why="AI Ready7 items 1.2 (unmanaged AI usage) and 2.1 (AI policy & acceptable use) had no dedicated control; shadow AI is a leading source of data leakage."),
    dict(domain="Governance & Leadership", id="GL-6", topic="AI Portfolio Governance & Value Realisation",
         statement="The organisation shall operate a structured intake, prioritisation and approval process for AI use cases based on business value, feasibility, data readiness, risk and strategic fit.\nExpected financial and non-financial benefits shall be defined before approval and actual outcomes shall be tracked, with under-performing or high-risk initiatives re-assessed, re-scoped or retired.",
         refs="ISO42001:6.2 A.6.1.2\nNIST AI RMF:Map 1.4 Map 3.1 Map 3.2 Govern 1.1\nSOC2:CC3.1",
         activities=["Implement a standard AI use-case intake form capturing objective, owner, data, users, expected benefits and preliminary risk tier",
                     "Score and prioritise use cases against value, feasibility, data readiness, risk and strategic alignment",
                     "Define KPIs / ROI targets and a benefits-realisation owner at approval",
                     "Review portfolio performance quarterly (value delivered, cost, risk posture) and decide continue / pivot / stop",
                     "Report portfolio status to executive sponsor / AI committee"],
         evidence=["Use-case intake records and prioritisation scoring",
                   "Approved business cases with benefit KPIs",
                   "Quarterly portfolio performance reports and decisions",
                   "Records of retired or re-scoped initiatives"],
         tests=["Select a sample of live AI use cases and confirm each passed intake and approval",
                "Verify KPIs were defined pre-approval and are measured",
                "Inspect the latest portfolio review for documented decisions",
                "Confirm no AI system in the inventory (GL-8) lacks an approved use case",
                "Pass criterion: 100% of sampled use cases approved with defined KPIs; portfolio reviewed at least quarterly"],
         iso="Cl. 6.2", add="ISO/IEC 42001 Annex B (objectives)\nISO/IEC 38507:2022",
         gcc="iGA General Policy for the Use of AI - Pillar 2",
         r7="1.2, 1.3", app="Both", typ="Directive", freq="Per use case; quarterly portfolio review",
         why="AI Ready7 items 1.2 and 1.3 (Portfolio governance, Value realisation) were not covered - GT Bahrain scored 50% in Business Alignment."),
    dict(domain="Governance & Leadership", id="GL-7", topic="AI Oversight Committee & Centre of Excellence",
         statement="The organisation shall establish a cross-functional AI oversight body (AI committee / Centre of Excellence) with a documented charter, decision rights and escalation paths, responsible for approving high-risk AI use cases, maintaining guardrails and standards, and advising on responsible AI practice.\nMembership shall include business, technology, data, legal/compliance, privacy, security and risk expertise, and decisions shall be minuted.",
         refs="ISO42001:5.3 A.3.2 A.3.3\nNIST AI RMF:Govern 2.1 Govern 3.1 Govern 4.1\nSOC2:CC1.2 CC1.3",
         activities=["Approve a charter defining scope, membership, quorum, decision rights and escalation to executive/board",
                     "Define which risk tiers require committee approval (e.g., High / Critical per RM-5)",
                     "Publish practical guardrails and reusable patterns (permitted use cases, data handling, bias, transparency, human oversight)",
                     "Meet at a defined cadence and minute all approvals, conditions and rejections",
                     "Report to the board / executive committee at least semi-annually"],
         evidence=["Committee / CoE charter and membership list",
                   "Meeting minutes, decision log and approval conditions",
                   "Published guardrails, standards and patterns",
                   "Board / executive reporting packs"],
         tests=["Inspect charter for decision rights and escalation",
                "Trace a sample of High/Critical tier use cases to committee approval records",
                "Verify membership covers all required disciplines and quorum was met",
                "Confirm guardrails are published and version-controlled",
                "Pass criterion: all High/Critical use cases approved by the committee before deployment"],
         iso="Cl. 5.3; A.5.2", add="NSW AIAF - AI Review Committee (AIRC) escalation model\nIEEE 7000-2021",
         gcc="GCC Guiding Manual on the Ethics of AI Use\nCBB Rulebook HC Module - board committees (licensees)",
         r7="2.3", app="Both", typ="Directive", freq="Monthly / per approval; semi-annual board report",
         why="AI Ready7 item 2.3 recommends a centre of excellence for guardrails; the RCM had roles (GL-2) but no oversight body with approval rights."),
    dict(domain="Governance & Leadership", id="GL-8", topic="AI System Inventory & Ownership Register",
         statement="The organisation shall maintain a complete and current inventory (AI register) of all AI systems, models, agents and AI-enabled third-party services in development or use, from ideation to retirement.\nEach entry shall record the business owner, technical owner, purpose, lifecycle stage, risk tier, data categories processed, regulatory role (e.g., provider / deployer), key dependencies and assessment status.",
         refs="ISO42001:A.4.2 A.4.3 A.6.2.2\nEU AI ACT:26 49 71\nNIST AI RMF:Govern 1.6\nSOC2:CC2.1",
         activities=["Define mandatory register fields and ownership responsibilities",
                     "Register every AI system at intake and update at each lifecycle gate",
                     "Reconcile the register quarterly against procurement, cloud/SaaS discovery and CMDB data",
                     "Record regulatory role and EU database registration status where applicable",
                     "Report register completeness and risk-tier distribution to the AI committee"],
         evidence=["AI register extract with owners and risk tiers",
                   "Quarterly reconciliation evidence",
                   "Register change history",
                   "Committee reports on register completeness"],
         tests=["Obtain the AI register and verify mandatory fields are populated",
                "Compare against procurement records and SaaS discovery to identify unregistered AI",
                "Trace a sample of register entries to named business and technical owners",
                "Verify retired systems are marked and decommissioning evidence is linked (LC-10)",
                "Pass criterion: no unregistered AI systems identified; 100% entries have owners and risk tier"],
         iso="A.5.9, A.5.10", add="NSW AIAF / Australian Guidance for AI Adoption - AI register template\nOMB M-25-21 AI use-case inventory practice",
         gcc="iGA General Policy for the Use of AI (inventory of government AI use)",
         r7="2.5", app="Both", typ="Directive", freq="Continuous; quarterly reconciliation",
         why="LC-3 covers resource inventories but not a use-case level AI register with ownership; AI Ready7 item 2.5 and most regulations presuppose one."),
    # ---------------------------------------------------------------- Risk Management
    dict(domain="Risk Management", id="RM-5", topic="AI Use-Case Risk Classification & Prohibited Practice Screening",
         statement="The organisation shall screen every AI use case at intake against prohibited practices and classify it into a defined risk tier (e.g., Low, Medium, High, Critical) using documented criteria including decision impact, autonomy, data sensitivity, affected population, reversibility and regulatory classification (e.g., EU AI Act Annex III high-risk).\nThe assigned tier shall determine the depth of assessment, required controls, approval authority and review frequency.",
         refs="ISO42001:6.1.2 A.5.2\nEU AI ACT:5 6 Annex III\nNIST AI RMF:Map 1.1 Map 1.5 Map 5.1",
         activities=["Maintain a prohibited-practices checklist (e.g., manipulative techniques, social scoring, untargeted facial scraping, emotion recognition at work/education)",
                     "Apply a standard tiering questionnaire at intake and on material change",
                     "Document regulatory classification (EU AI Act high-risk, GPAI, transparency-only) where applicable",
                     "Link tier to mandatory control set, approval authority (GL-7) and review cadence",
                     "Re-tier systems at least annually and upon change in purpose, data, autonomy or user population"],
         evidence=["Prohibited-practice screening records",
                   "Completed tiering questionnaires with rationale",
                   "Tier-to-control requirement matrix",
                   "Re-tiering records"],
         tests=["Select a sample of use cases and re-perform tiering to confirm consistency",
                "Verify prohibited-practice screening was completed before development/procurement",
                "Confirm High/Critical systems received the mandated control set and approvals",
                "Check re-tiering occurred after documented material changes",
                "Pass criterion: no deployed system lacks a tier; re-performed tier matches in >= 90% of samples"],
         iso="Cl. 6.1.2", add="ISO/IEC 23894:2023 cl.6.4\nNSW AIAF risk bands (Low / Medium / High / Critical)\nKorea AI Basic Act ('high-impact AI')\nColorado SB 24-205 ('high-risk AI system')",
         gcc="Bahrain draft AI Regulation Law (risk-based obligations - pending)\nSDAIA AI Ethics Principles risk levels (KSA)",
         r7="2.4", app="Both", typ="Preventive", freq="At intake; annual re-tiering",
         why="Prohibitions (EU AI Act Art. 5) have applied since 2 Feb 2025; the RCM referenced them but had no operational screening/tiering control that drives proportionate controls."),
    dict(domain="Risk Management", id="RM-6", topic="AI Risk Appetite, Tolerances & Key Risk Indicators",
         statement="The organisation shall define and approve an AI risk appetite statement with measurable tolerances for key AI risk categories (e.g., accuracy degradation, bias, privacy, security, third-party concentration, reputational harm).\nKey risk indicators (KRIs) with thresholds and mandatory responses shall be monitored and reported, and breaches shall be escalated for decision.",
         refs="ISO42001:6.1.1 6.1.2 9.1\nNIST AI RMF:Govern 1.3 Map 1.5 Measure 1.1 Manage 1.1\nSOC2:CC3.1 CC3.2",
         activities=["Draft and obtain board/executive approval of an AI risk appetite statement",
                     "Define KRIs with green/amber/red thresholds for each risk category and each High/Critical system",
                     "Automate KRI collection where possible (e.g., drift, error rates, override rates, incidents)",
                     "Define mandatory responses for threshold breaches (e.g., throttle, human review, rollback, suspend)",
                     "Report KRI dashboard quarterly and escalate breaches"],
         evidence=["Approved risk appetite statement",
                   "KRI library with thresholds and owners",
                   "KRI dashboards and breach logs",
                   "Escalation and response records"],
         tests=["Confirm risk appetite approval date and approver",
                "Verify KRIs exist for all High/Critical systems",
                "Trace a sample of threshold breaches to documented responses",
                "Confirm quarterly reporting to governance forum",
                "Pass criterion: all breaches escalated and responded to within defined timelines"],
         iso="Cl. 6.1.1, 9.1", add="ISO/IEC 23894:2023\nISO 31000:2018\nAI Ready7 recommendation 4.4 (risk measurement layer with KRIs)",
         gcc="CBB Rulebook RM Module - risk appetite (licensees)",
         r7="1.1, 4.4", app="Both", typ="Detective", freq="Annual appetite; KRIs continuous / quarterly report",
         why="AI Ready7 recommendations 1.1 and 4.4 require defined risk appetite and KRIs with mandatory responses; RM-1 referenced tolerance only generically."),
    # ---------------------------------------------------------------- Regulatory Operations
    dict(domain="Regulatory Operations", id="RO-5", topic="Regulatory Horizon Scanning & Obligations Register",
         statement="The organisation shall maintain a register of AI-relevant legal, regulatory, supervisory and contractual obligations for each jurisdiction in which it develops, deploys or provides AI (including extraterritorial regimes such as the EU AI Act), mapped to owners and controls.\nThe organisation shall monitor regulatory developments, assess impact, and update policies and controls before obligations take effect.",
         refs="ISO42001:4.1 4.2 6.1.3\nEU AI ACT:2 113\nNIST AI RMF:Govern 1.1\nSOC2:CC1.5 CC3.4",
         activities=["Identify applicable jurisdictions and regimes (e.g., Bahrain PDPL, iGA AI policy, CBB rules, EU AI Act, KSA/UAE regimes)",
                     "Maintain an obligations register mapping each requirement to RCM controls and owners",
                     "Perform monthly horizon scanning and document impact assessments for new/changed requirements",
                     "Track key effective dates (e.g., EU AI Act 2 Aug 2026 / 2 Aug 2027) and readiness actions",
                     "Report regulatory change status to the AI committee"],
         evidence=["Obligations register with control mapping",
                   "Horizon-scanning logs and impact assessments",
                   "Readiness trackers for upcoming effective dates",
                   "Committee reporting"],
         tests=["Verify the register covers all jurisdictions of operation and AI market exposure",
                "Select recent regulatory developments and confirm they were logged and assessed",
                "Trace a sample of obligations to implemented controls",
                "Confirm readiness plans exist for obligations effective within 12 months",
                "Pass criterion: no applicable obligation without an owner and control mapping"],
         iso="A.5.31", add="EU AI Act Art. 113 (phased application) and Digital Omnibus proposal (Nov 2025) - monitor final adopted timelines\nKorea AI Basic Act; Japan AI Promotion Act (2025); China AI-generated content labelling measures (effective 1 Sep 2025)",
         gcc="Bahrain draft AI Regulation Law (pending)\nBahrain PDPL; iGA General Policy for the Use of AI (2025)\nGCC Guiding Manual on the Ethics of AI Use\nKSA SDAIA AI Ethics Principles; UAE Charter for AI (2024); DIFC Regulation 10; QCB AI Guideline (2024)",
         r7="2.2", app="Both", typ="Directive", freq="Monthly scanning; quarterly reporting",
         why="RO-1 addressed compliance generally but there was no multi-jurisdiction obligations register - critical for Bahrain entities exposed to GCC and EU regimes."),
    dict(domain="Regulatory Operations", id="RO-6", topic="Deployer Obligations for High-Risk AI",
         statement="Where the organisation deploys high-risk AI systems, it shall use them in accordance with the provider's instructions for use, assign competent human oversight, ensure input data is relevant and representative, monitor operation and inform the provider of risks or serious incidents, retain automatically generated logs, inform affected workers and persons subject to decisions, and perform a fundamental rights impact assessment where required.",
         refs="ISO42001:A.9.2 A.9.3 A.9.4\nEU AI ACT:26.1-26.11 27 86\nNIST AI RMF:Govern 6.1 Manage 3.1",
         activities=["Identify all deployed high-risk AI systems and obtain provider instructions for use",
                     "Assign named, trained human-oversight persons for each system (link GL-4, RS-1)",
                     "Validate relevance/representativeness of input data under the deployer's control",
                     "Retain automatically generated logs for at least six months (or longer where required)",
                     "Notify workers' representatives before workplace deployment and inform affected persons of AI-assisted decisions",
                     "Complete a fundamental rights impact assessment before first use where required (e.g., public bodies, credit scoring, life/health insurance pricing)"],
         evidence=["Inventory of deployed high-risk systems with instructions for use",
                   "Oversight assignments and training records",
                   "Log retention configuration evidence",
                   "Worker / affected-person notices",
                   "FRIA records and notification to authority where required"],
         tests=["Confirm each deployed high-risk system has instructions for use on file and is operated within them",
                "Verify oversight persons are assigned and trained",
                "Inspect log retention settings (>= 6 months)",
                "Sample decisions and confirm affected persons were informed",
                "Pass criterion: all Art. 26 duties evidenced for each in-scope system"],
         iso="A.5.31, A.8.15", add="EU AI Act Art. 26 & 27 (apply from 2 Aug 2026 for Annex III systems, subject to final Digital Omnibus outcome)\nISO/IEC 42005:2025",
         gcc="CBB Rulebook - business conduct & consumer protection (credit/insurance use cases)",
         r7="2.2, 5.2", app="Deployer", typ="Preventive", freq="Per system; continuous",
         why="The RCM was provider-centric; most Bahrain organisations (banks, insurers, government) will be deployers, whose Art. 26/27 duties were largely unmapped."),
    # ---------------------------------------------------------------- Lifecycle
    dict(domain="System, Data and Model Lifecycle", id="LC-6", topic="General-Purpose AI & Foundation Model Governance",
         statement="The organisation shall govern the selection, adaptation (e.g., fine-tuning, retrieval-augmentation) and use of general-purpose AI (GPAI) and foundation models, including evaluation of model capabilities, limitations, licence terms, training-data transparency and provider compliance.\nWhere the organisation places a GPAI model on the market or substantially modifies one, it shall maintain technical documentation, provide downstream information, implement a copyright policy and publish a training-content summary as required.",
         refs="ISO42001:A.6.1.3 A.7.3 A.10.3\nEU AI ACT:53 55 56 Annex XI Annex XII\nNIST AI RMF:Map 4.1 Govern 6.1",
         activities=["Maintain an approved foundation-model list with evaluation results (quality, safety, bias, security, cost)",
                     "Review model licences, acceptable-use terms and provider GPAI compliance (e.g., Code of Practice signatory status)",
                     "Evaluate models against use-case specific benchmarks before adoption and after provider version changes",
                     "For fine-tuned / provided models: maintain Annex XI/XII documentation, copyright policy and training-content summary",
                     "Pin model versions and monitor provider deprecation notices"],
         evidence=["Approved model list and evaluation reports",
                   "Licence and provider due-diligence records",
                   "Version-pinning configuration and change records",
                   "GPAI documentation pack where the organisation is a provider"],
         tests=["Verify each production foundation model is on the approved list with a current evaluation",
                "Inspect licence review for a sample of models",
                "Confirm model version changes triggered re-evaluation",
                "Where applicable, inspect Art. 53 documentation and training-content summary",
                "Pass criterion: no unapproved or unpinned foundation model in production"],
         iso="A.5.19, A.5.23", add="EU GPAI Code of Practice (July 2025)\nNIST AI 600-1 (GAI profile)\nStanford Foundation Model Transparency Index (reference)",
         gcc="SDAIA Generative AI Guidelines (KSA, 2024)\niGA General Policy for the Use of AI",
         r7="4.5, 6.2", app="Both", typ="Preventive", freq="At adoption; on provider version change",
         why="GPAI obligations (EU AI Act Art. 53-55) have applied since 2 Aug 2025 and most enterprise AI now relies on foundation models; no control existed."),
    dict(domain="System, Data and Model Lifecycle", id="LC-7", topic="Generative AI Output Integrity & Content Provenance",
         statement="The organisation shall implement controls to manage the accuracy, reliability and provenance of generative AI outputs, including grounding and citation mechanisms, hallucination testing, human verification for material outputs, and machine-readable marking of synthetic content.\nDeep-fake or AI-manipulated image, audio, video or text published to inform the public shall be disclosed as AI-generated.",
         refs="ISO42001:A.6.2.4 A.8.2\nEU AI ACT:50.2 50.4\nNIST AI RMF:Measure 2.5 Measure 2.9",
         activities=["Define verification requirements by output materiality (e.g., client deliverables, regulatory filings, public content)",
                     "Implement retrieval grounding, citations and confidence signals for knowledge-based assistants",
                     "Test for hallucination / factual error rates before release and monitor in production",
                     "Apply watermarking / content credentials (e.g., C2PA) to synthetic media where technically feasible",
                     "Disclose AI-generated or manipulated content to recipients where required"],
         evidence=["Output verification standard",
                   "Hallucination / factuality test results",
                   "Content-provenance / watermark configuration",
                   "Disclosure templates and samples"],
         tests=["Sample client-facing AI-assisted outputs and confirm documented human verification",
                "Review hallucination test results against acceptance thresholds",
                "Verify synthetic media carries provenance marking",
                "Confirm disclosure labels on published AI-generated content",
                "Pass criterion: 100% of sampled material outputs verified; thresholds met"],
         iso="A.5.37", add="C2PA Content Credentials specification\nNIST AI 600-1 (confabulation, information integrity)\nNIST AI 100-4 (reducing risks posed by synthetic content)\nChina Measures for Labelling AI-Generated Content (2025)",
         gcc="SDAIA Deepfakes Guidelines (KSA)\nGCC Guiding Manual on the Ethics of AI Use (Transparency)",
         r7="1.4, 3.2", app="Both", typ="Preventive", freq="Per release; continuous monitoring",
         why="Generative-AI specific risks (confabulation, synthetic content, Art. 50(2)/(4) marking duties from 2 Aug 2026) were only indirectly addressed in CO-1."),
    dict(domain="System, Data and Model Lifecycle", id="LC-8", topic="Agentic AI & Autonomous Action Controls",
         statement="The organisation shall define and enforce execution authority, trust boundaries and least-privilege permissions for AI agents and AI systems able to take actions (e.g., calling tools/APIs, executing code, sending communications, initiating transactions).\nAgent actions shall be bounded by allow-lists, rate and value limits, human approval for high-impact actions, full action logging, and an immediate stop (kill-switch) capability.",
         refs="ISO42001:A.6.2.3 A.9.2\nEU AI ACT:14 15\nNIST AI RMF:Govern 1.7 Manage 2.4\nSOC2:CC6.1 CC6.3",
         activities=["Classify agent actions by impact and define which require human-in-the-loop approval",
                     "Issue each agent a distinct non-human identity with scoped, short-lived credentials",
                     "Restrict tools / APIs / MCP servers via allow-lists and validate tool inputs/outputs",
                     "Apply transaction, rate and spend limits and sandbox code execution",
                     "Log all agent reasoning traces and actions; implement and test kill-switch / rollback"],
         evidence=["Agent inventory with permissions and action classification",
                   "Non-human identity and credential configuration",
                   "Tool allow-lists and guardrail configuration",
                   "Action logs and kill-switch test records"],
         tests=["Review a sample of agents for least-privilege scopes and credential lifetime",
                "Attempt an unapproved tool call / action in test to confirm it is blocked",
                "Verify high-impact actions required human approval in logs",
                "Confirm kill-switch was tested within the last 6 months",
                "Pass criterion: no agent with standing privileged credentials; all high-impact actions approved"],
         iso="A.5.15, A.5.18, A.8.2, A.8.15", add="OWASP Top 10 for Agentic Applications (Dec 2025)\nOWASP LLM06:2025 Excessive Agency\nSingapore IMDA Model AI Governance Framework for Agentic AI (Jan 2026)\nDIFC Regulation 10 (autonomous & semi-autonomous systems)",
         gcc="DIFC Regulation 10 (UAE)\nCBB Rulebook OM Module - access control (licensees)",
         r7="4.2, 6.1", app="Both", typ="Preventive", freq="Per agent; continuous",
         why="AI Ready7 item 4.2 (execution authority & trust boundaries) and 6.1 (agent credentials) - agentic AI risks were absent from the RCM."),
    dict(domain="System, Data and Model Lifecycle", id="LC-9", topic="Independent Model Validation & Model Risk Management",
         statement="The organisation shall subject material AI/ML models to independent validation before first use and periodically thereafter, covering conceptual soundness, data suitability, performance, stability, bias, explainability, limitations and implementation.\nValidation findings shall be tracked to closure and models shall be risk-rated in a model inventory with defined validation frequencies.",
         refs="ISO42001:A.6.2.4 9.1\nEU AI ACT:9.6 9.8 15\nNIST AI RMF:Measure 2.1 Measure 2.3 Measure 2.5",
         activities=["Define a model risk management (MRM) policy and model risk tiering",
                     "Perform independent validation by a function separate from model development",
                     "Test performance on out-of-time / out-of-sample data, stability and sensitivity",
                     "Document limitations, compensating controls and conditions of use",
                     "Re-validate on material change and at tier-based frequency (e.g., annually for Tier 1)"],
         evidence=["MRM policy and model inventory with risk tiers",
                   "Independent validation reports",
                   "Findings tracker and closure evidence",
                   "Re-validation schedule"],
         tests=["Confirm validator independence from the development team",
                "Inspect a sample of validation reports for required scope",
                "Verify overdue validations and open high findings are escalated",
                "Confirm models are not used outside validated conditions",
                "Pass criterion: all Tier 1 models validated within the last 12 months"],
         iso="A.8.29", add="US Fed/OCC SR 11-7 (model risk management)\nUK PRA SS1/23 (model risk management principles, effective May 2024)\nISO/IEC 25059:2023",
         gcc="CBB Rulebook RM / CA modules - model use in credit and capital (licensees)\nQCB AI Guideline (Qatar, 2024)",
         r7="4.4, 6.3", app="Both", typ="Detective", freq="Pre-deployment; tier-based periodic",
         why="Financial-sector clients (CBB licensees) require model-risk-management style validation; RS-6 covered metrics but not independent validation."),
    dict(domain="System, Data and Model Lifecycle", id="LC-10", topic="AI System Retirement & Decommissioning",
         statement="The organisation shall plan and execute the controlled retirement of AI systems, models and agents, including stakeholder notification, transition or fallback arrangements, revocation of credentials and integrations, secure archival or disposal of models, training data, prompts and logs in line with retention obligations, and update of the AI register.",
         refs="ISO42001:A.6.2.5 A.7.6\nEU AI ACT:18 19 20\nNIST AI RMF:Manage 2.4 Govern 1.7",
         activities=["Define retirement triggers (end of value, unacceptable risk, provider deprecation, regulatory change)",
                     "Prepare a retirement plan with fallback process and stakeholder communication",
                     "Revoke API keys, service accounts, agent identities and integrations",
                     "Archive or securely delete models, datasets, embeddings/vector stores and logs per retention schedule",
                     "Update the AI register and close associated risks"],
         evidence=["Retirement plans and approvals",
                   "Credential revocation evidence",
                   "Secure disposal / archival certificates",
                   "Updated AI register entries"],
         tests=["Select retired systems and verify an approved retirement plan",
                "Confirm credentials and integrations were revoked",
                "Verify data/model disposal or archival aligns to retention requirements",
                "Confirm AI register status updated",
                "Pass criterion: no active credentials or data stores remain for retired systems"],
         iso="A.5.11, A.7.14, A.8.10", add="ISO/IEC 5338:2023 (retirement stage)\nNSW AIAF lifecycle phase 'Retirement'",
         gcc="Bahrain PDPL - retention limitation",
         r7="6.4", app="Both", typ="Corrective", freq="Per retirement event",
         why="AI Ready7 item 6.4 calls for retirement and secure disposal; LC-2 mentioned decommissioning only in passing."),
    dict(domain="System, Data and Model Lifecycle", id="LC-11", topic="Data Rights, Intellectual Property & Copyright",
         statement="The organisation shall verify that it holds the necessary rights to use data and content for AI training, fine-tuning, retrieval and prompting, respects text-and-data-mining opt-outs and licence restrictions, and manages intellectual-property risk in AI-generated outputs, including client confidentiality obligations and ownership of deliverables.",
         refs="ISO42001:A.7.3 A.7.5\nEU AI ACT:53.1c 53.1d\nNIST AI RMF:Govern 1.1 Map 4.1",
         activities=["Record data source, licence and permitted use for every training / retrieval dataset",
                     "Screen datasets for copyright, confidentiality and TDM opt-out restrictions",
                     "Obtain client consent where client data is used to improve models",
                     "Define ownership and IP disclaimer positions for AI-assisted deliverables",
                     "Assess vendor IP indemnities for GenAI services"],
         evidence=["Dataset provenance and licence register",
                   "IP / copyright screening records",
                   "Client consent records",
                   "Contract clauses on IP and indemnity"],
         tests=["Trace a sample of datasets to documented rights of use",
                "Verify client data is not used for training without consent",
                "Inspect vendor contracts for IP indemnity",
                "Confirm engagement letters address AI-assisted deliverables",
                "Pass criterion: 100% of sampled datasets with documented rights"],
         iso="A.5.32", add="EU DSM Directive 2019/790 Art. 4 (TDM opt-out)\nEU GPAI Code of Practice - Copyright chapter",
         gcc="Bahrain Law No. 22 of 2006 on Copyright and Neighbouring Rights\nBahrain PDPL (purpose limitation)",
         r7="2.2, 5.1", app="Both", typ="Preventive", freq="Per dataset / per contract",
         why="Copyright and data-rights obligations for AI (Art. 53(1)(c)-(d)) and professional-services confidentiality were not addressed."),
    # ---------------------------------------------------------------- Security
    dict(domain="Security", id="SE-6", topic="Adversarial ML & LLM Application Security",
         statement="The organisation shall protect AI systems against AI-specific attacks including prompt injection (direct and indirect), jailbreaks, data and model poisoning, model evasion, model extraction/inversion, insecure output handling, system-prompt leakage and unbounded resource consumption, through layered input/output guardrails, secure design patterns and continuous testing.",
         refs="ISO42001:A.6.2.4\nEU AI ACT:15.5\nNIST AI RMF:Measure 2.7 Manage 2.3\nSOC2:CC7.1",
         activities=["Threat-model each AI system using OWASP LLM Top 10 / MITRE ATLAS",
                     "Deploy input and output filtering (prompt-injection detection, content policy, PII redaction)",
                     "Separate trusted instructions from untrusted content (e.g., retrieved documents, emails) and constrain tool use",
                     "Validate training / fine-tuning data integrity to detect poisoning",
                     "Rate-limit and monitor for extraction patterns and resource abuse"],
         evidence=["AI threat models",
                   "Guardrail configurations and test results",
                   "Data integrity validation records",
                   "Security monitoring alerts and responses"],
         tests=["Inspect threat models for coverage of OWASP LLM Top 10 categories",
                "Execute a sample of prompt-injection and jailbreak test cases",
                "Verify output encoding / sanitisation before downstream use",
                "Confirm rate limits and anomaly alerts are configured",
                "Pass criterion: no critical test case bypasses guardrails; findings remediated within SLA"],
         iso="A.8.7, A.8.8, A.8.16, A.8.28", add="OWASP Top 10 for LLM Applications 2025\nMITRE ATLAS\nNIST AI 100-2 E2025\nETSI EN 304 223\nUK AI Cyber Security Code of Practice (2025)",
         gcc="Bahrain NCSC standards\nKSA NCA guidelines for secure use of AI (KSA operations)",
         r7="6.4, 6.5", app="Both", typ="Preventive", freq="Per release; continuous monitoring",
         why="SE-3 mentioned model poisoning only briefly; LLM-specific threats (prompt injection etc.) had no dedicated control. GT Bahrain scored 55% in Protect AI Systems."),
    dict(domain="Security", id="SE-7", topic="AI Supply Chain Security",
         statement="The organisation shall secure the AI supply chain, including third-party models, model weights, datasets, libraries, plugins, MCP servers and hosting platforms, by verifying provenance and integrity, scanning artefacts for malicious content, maintaining an AI bill of materials (AI-BOM), and monitoring for vulnerabilities and provider changes.",
         refs="ISO42001:A.10.3 A.4.3\nEU AI ACT:15.5 25.4\nNIST AI RMF:Govern 6.1 Map 4.1\nSOC2:CC9.2",
         activities=["Maintain an AI-BOM for each system (models, versions, datasets, libraries, plugins)",
                     "Obtain models only from approved registries; verify hashes / signatures",
                     "Scan model files for unsafe serialisation and embedded malicious code",
                     "Monitor dependencies and model sources for vulnerabilities and compromise",
                     "Assess third-party plugins / MCP servers before enablement"],
         evidence=["AI-BOM records",
                   "Model scanning and signature verification logs",
                   "Approved registry configuration",
                   "Vulnerability monitoring reports"],
         tests=["Select systems and verify an AI-BOM exists and is current",
                "Confirm model artefacts were scanned and signatures verified",
                "Verify plugins / MCP servers were approved before use",
                "Check vulnerability alerts were triaged within SLA",
                "Pass criterion: no unscanned model artefacts in production"],
         iso="A.5.19, A.5.21, A.5.23, A.8.8", add="OWASP LLM03:2025 Supply Chain\nCISA/NSA 'AI Data Security' (May 2025)\nCycloneDX ML-BOM / SPDX 3.0 AI profile\nSLSA framework",
         gcc="CBB Rulebook OM Module - outsourcing & third-party technology risk (licensees)",
         r7="6.2, 6.3", app="Both", typ="Preventive", freq="Per acquisition; continuous monitoring",
         why="AI supply-chain compromise (malicious models, poisoned datasets, rogue plugins) is a leading AI attack vector not addressed by TP-1/TP-2."),
    # ---------------------------------------------------------------- Safe Responsible AI
    dict(domain="Safe Responsible AI", id="RS-7", topic="Accessibility & Inclusion",
         statement="The organisation shall design, procure and operate AI systems and their user interfaces to be accessible to persons with disabilities and inclusive of diverse users (including language, literacy and digital access), and shall evaluate whether AI use creates exclusion or differential service quality for any group.",
         refs="ISO42001:A.5.4\nEU AI ACT:16.l\nNIST AI RMF:Map 1.2 Measure 2.11",
         activities=["Apply recognised accessibility standards (e.g., WCAG 2.2 AA) to AI interfaces",
                     "Support Arabic and English interaction and plain-language explanations where the user base requires it",
                     "Test AI performance across user groups (e.g., language, dialect, age)",
                     "Provide non-AI alternative channels for essential services",
                     "Include accessibility requirements in AI procurement"],
         evidence=["Accessibility test reports",
                   "Multilingual performance test results",
                   "Alternative channel documentation",
                   "Procurement requirements"],
         tests=["Inspect accessibility testing for customer-facing AI",
                "Review performance disaggregated by language / user group",
                "Confirm availability of a human / non-AI alternative",
                "Pass criterion: no material accessibility defects open on customer-facing AI"],
         iso="No direct equivalent", add="EU Accessibility Act (Directive 2019/882, applicable from 28 Jun 2025)\nWCAG 2.2\nUNESCO Recommendation on the Ethics of AI",
         gcc="GCC Guiding Manual on the Ethics of AI Use (Inclusiveness)\nUNESCO RAM Bahrain (2025) - inclusion recommendations",
         r7="2.3", app="Both", typ="Preventive", freq="Per release",
         why="Accessibility obligations (EU AI Act Art. 16(l)) and inclusion (Arabic-language performance) were not covered."),
    dict(domain="Safe Responsible AI", id="RS-8", topic="Environmental Sustainability of AI",
         statement="The organisation shall consider the environmental impact of AI systems, including energy, water and carbon associated with training, fine-tuning and inference, in model selection, architecture and vendor decisions, and shall measure and report AI-related resource consumption where material.",
         refs="ISO42001:A.5.4 6.2\nEU AI ACT:40.2 Annex XI\nNIST AI RMF:Measure 2.12",
         activities=["Include energy/carbon efficiency as a model and vendor selection criterion",
                     "Right-size models (prefer smaller / distilled models where fit for purpose)",
                     "Obtain energy and carbon data from cloud / AI providers",
                     "Report AI resource consumption in ESG / sustainability reporting where material"],
         evidence=["Model selection records including efficiency criteria",
                   "Provider energy / carbon reports",
                   "Sustainability reporting extracts"],
         tests=["Verify efficiency criteria were applied in recent model selections",
                "Confirm provider energy data is collected for material workloads",
                "Pass criterion: AI resource consumption measured for all material workloads"],
         iso="No direct equivalent", add="ISO/IEC TR 20226 (environmental sustainability aspects of AI systems)\nOECD 'Measuring the environmental impacts of AI compute'\nGHG Protocol Scope 2/3",
         gcc="Bahrain National Energy Efficiency Action Plan / Net-Zero 2060 commitment",
         r7="4.5", app="Both", typ="Directive", freq="Annual",
         why="Environmental impact is an ISO/IEC 42001 impact consideration and an EU AI Act documentation item for GPAI; not represented."),
    dict(domain="Safe Responsible AI", id="RS-9", topic="Workforce Impact & Worker Information",
         statement="The organisation shall assess the impact of AI adoption on roles, skills and working conditions, inform and consult workers (and their representatives where applicable) before deploying AI that affects them, and plan reskilling and job-redesign measures to support a responsible transition.",
         refs="ISO42001:A.5.4 7.4\nEU AI ACT:26.7\nNIST AI RMF:Govern 3.2 Map 3.4",
         activities=["Perform workforce impact assessments for AI initiatives affecting roles",
                     "Communicate with and consult affected staff prior to deployment",
                     "Prohibit prohibited workplace uses (e.g., emotion recognition in the workplace)",
                     "Link impacted roles to reskilling pathways (GL-4)"],
         evidence=["Workforce impact assessments",
                   "Staff communications / consultation records",
                   "Reskilling plans and participation"],
         tests=["Confirm impact assessments exist for AI affecting job roles",
                "Verify workers were informed before deployment",
                "Pass criterion: no workplace AI deployed without documented worker information"],
         iso="A.6.3", add="ILO guidance on AI and the world of work\nOECD AI Principle 2.4",
         gcc="Bahrain Labour Law for the Private Sector (Law No. 36 of 2012)\nBahrain Labour Fund (Tamkeen) reskilling programmes",
         r7="3.4", app="Deployer", typ="Directive", freq="Per deployment",
         why="AI Ready7 item 3.4 references workforce planning and job-anxiety concerns; EU AI Act Art. 26(7) requires informing workers."),
    # ---------------------------------------------------------------- Privacy
    dict(domain="Privacy", id="PR-5", topic="Automated Decision-Making & Data-Subject Rights in AI",
         statement="The organisation shall identify AI-supported decisions producing legal or similarly significant effects on individuals, ensure a lawful basis and meaningful human involvement, and enable individuals to exercise their rights (information, access, objection, rectification, erasure and contesting automated decisions) including where personal data is embedded in models, embeddings or prompts.",
         refs="ISO42001:A.8.2 A.9.2\nEU AI ACT:26.11 86\nNIST AI RMF:Govern 1.1 Measure 2.10\nSOC2:P4.1 P5.1",
         activities=["Map AI-supported decisions with significant effects and document lawful basis",
                     "Provide notices describing logic involved and consequences of automated processing",
                     "Implement procedures to fulfil data-subject requests across training data, vector stores, logs and outputs",
                     "Provide human review on request for automated decisions",
                     "Assess feasibility of rectification/erasure (e.g., machine unlearning, retraining, suppression)"],
         evidence=["ADM register and lawful-basis records",
                   "Privacy notices referencing AI processing",
                   "Data-subject request logs involving AI systems",
                   "Human review records"],
         tests=["Sample AI-supported decisions and confirm notice and human review availability",
                "Trace data-subject requests through AI data stores",
                "Confirm response timelines met",
                "Pass criterion: all significant ADM identified with safeguards"],
         iso="A.5.34", add="GDPR Art. 13(2)(f), 15(1)(h), 21, 22\nCJEU C-634/21 SCHUFA (2023) - scoring as automated decision",
         gcc="Bahrain PDPL - data-subject rights (access, objection, rectification, erasure)\nKSA PDPL; UAE Federal Decree-Law 45/2021",
         r7="5.2, 5.5", app="Both", typ="Preventive", freq="Continuous",
         why="Rights relating to automated decisions and personal data inside models/embeddings were not explicitly covered by PR-1 to PR-4."),
    dict(domain="Privacy", id="PR-6", topic="Cross-Border Transfers & Data Residency for AI Services",
         statement="The organisation shall identify where AI services process and store data (including prompts, outputs, logs and fine-tuning data), ensure cross-border transfers comply with applicable data-protection, data-residency and sectoral requirements, and prefer in-region hosting for sensitive or regulated data.",
         refs="ISO42001:A.7.2 A.10.3\nNIST AI RMF:Map 4.1\nSOC2:C1.1 P6.1",
         activities=["Document data flows and hosting regions for each AI service",
                     "Assess transfers against Bahrain PDPL transfer rules and sectoral restrictions",
                     "Implement transfer safeguards (contractual clauses, approvals) or select in-region deployment",
                     "Verify vendor commitments on data retention and no-training on customer data"],
         evidence=["AI data-flow maps with hosting regions",
                   "Transfer assessments and approvals",
                   "Vendor data-processing agreements"],
         tests=["Confirm hosting region for a sample of AI services",
                "Verify transfer assessments exist where data leaves Bahrain",
                "Inspect DPAs for retention and no-training clauses",
                "Pass criterion: no unassessed cross-border transfer of personal or regulated data"],
         iso="A.5.14, A.5.34", add="GDPR Chapter V\nISO/IEC 27018",
         gcc="Bahrain PDPL - cross-border transfer requirements\nLegislative Decree No. 56 of 2018 (cloud computing services to foreign parties)\nCBB Rulebook - outsourcing / data location (licensees)\nKSA PDPL Transfer Regulation",
         r7="5.1, 6.2", app="Deployer", typ="Preventive", freq="Per service; annual review",
         why="Most GenAI services process data outside Bahrain; data-residency and PDPL transfer requirements were not addressed."),
    # ---------------------------------------------------------------- Third Party
    dict(domain="Third Party & Supply Chain", id="TP-3", topic="AI Procurement & Contractual Safeguards",
         statement="The organisation shall apply AI-specific due diligence and contractual safeguards when procuring AI systems or AI-enabled services, covering data use (including no training on customer data without consent), confidentiality, security, transparency and documentation, model-change notification, performance and bias commitments, incident notification, audit rights, IP indemnity, sub-processor controls and exit/portability.",
         refs="ISO42001:A.10.2 A.10.3\nEU AI ACT:25.4\nNIST AI RMF:Govern 6.1 Govern 6.2\nSOC2:CC9.2",
         activities=["Use an AI vendor due-diligence questionnaire in procurement",
                     "Embed standard AI clauses in contracts (data use, model changes, incidents, audit, IP, exit)",
                     "Require vendors to disclose AI features embedded in existing products",
                     "Review vendor compliance evidence (e.g., ISO/IEC 42001 certification, SOC 2, model cards)",
                     "Monitor vendor AI changes and re-assess on material change"],
         evidence=["Completed AI due-diligence questionnaires",
                   "Contract templates and executed AI clauses",
                   "Vendor certifications / assurance reports",
                   "Change notifications and re-assessments"],
         tests=["Sample AI contracts and confirm presence of mandatory AI clauses",
                "Verify due diligence completed before signature",
                "Confirm vendor assurance evidence is current",
                "Pass criterion: all new AI contracts contain mandatory clauses"],
         iso="A.5.19, A.5.20, A.5.21, A.5.22", add="EU Model Contractual AI Clauses (MCC-AI, 2025 update)\nISO/IEC 42001 certification of vendors\nOMB M-25-22 (AI acquisition practice)",
         gcc="CBB Rulebook OM Module - outsourcing (licensees)\nBahrain Tender Board regulations (public sector)",
         r7="6.2, 2.4", app="Deployer", typ="Preventive", freq="Per procurement; on vendor change",
         why="AI Ready7 item 6.2 calls for vendor/third-party contractual protections; TP-1/TP-2 lacked AI-specific clauses."),
    # ---------------------------------------------------------------- Transparency
    dict(domain="Transparency & Communication", id="CO-3", topic="Contestability, Appeal & Redress",
         statement="The organisation shall provide individuals affected by AI-supported decisions with accessible means to challenge outcomes, obtain an explanation, request human review and obtain timely redress, and shall use contest outcomes to improve AI systems.",
         refs="ISO42001:A.8.3 A.8.5\nEU AI ACT:85 86\nNIST AI RMF:Govern 5.1 Manage 4.1",
         activities=["Publish channels for challenging AI-supported decisions",
                     "Define time-bound review and redress procedures with human decision-makers",
                     "Provide explanations of the main elements of AI-supported decisions on request",
                     "Analyse contest outcomes for systemic issues and feed into OM-3 / IM-3"],
         evidence=["Published contest / appeal procedures",
                   "Case logs with timelines and outcomes",
                   "Trend analysis and resulting improvements"],
         tests=["Confirm channel availability for customer-facing AI decisions",
                "Sample appeal cases and verify human review and timeliness",
                "Confirm trend analysis performed at least quarterly",
                "Pass criterion: 100% of sampled appeals reviewed by a human within SLA"],
         iso="No direct equivalent", add="NSW AIAF - Contestability principle\nColorado SB 24-205 (appeal / human review)\nGDPR Art. 22(3)",
         gcc="GCC Guiding Manual on the Ethics of AI Use\nCBB Rulebook - complaints handling (licensees)",
         r7="1.4, 5.2", app="Deployer", typ="Corrective", freq="Continuous; quarterly analysis",
         why="Contestability is a core principle in the AIAF and EU AI Act Art. 86; CO-2 covered feedback but not individual redress."),
    # ---------------------------------------------------------------- AI-enabled threats
    dict(domain="Protection from AI-Enabled Threats", id="AT-1", topic="AI-Specific Threat Intelligence",
         statement="The organisation shall collect, analyse and act on threat intelligence regarding AI-enabled attacks (e.g., AI-generated phishing, deepfake fraud, automated vulnerability discovery and exploit chaining) and attacks against AI systems (e.g., model poisoning, prompt injection campaigns), and incorporate it into risk assessments and defensive controls.",
         refs="ISO42001:6.1.2\nNIST AI RMF:Govern 6.1 Measure 3.1\nSOC2:CC3.2 CC7.1",
         activities=["Subscribe to AI-relevant threat feeds (e.g., MITRE ATLAS case studies, CERT advisories, vendor reports)",
                     "Produce periodic AI threat briefings for security, fraud and risk teams",
                     "Map emerging techniques to detection and control coverage",
                     "Share intelligence with sector peers and national CERT where appropriate"],
         evidence=["Threat intelligence sources and briefings",
                   "Coverage mapping updates",
                   "Information-sharing records"],
         tests=["Inspect latest AI threat briefings",
                "Confirm new techniques were mapped to control/detection updates",
                "Pass criterion: AI threat intelligence reviewed at least monthly"],
         iso="A.5.7", add="MITRE ATLAS\nENISA Threat Landscape\nFinCEN Alert FIN-2024-Alert004 (deepfake fraud)",
         gcc="Bahrain NCSC threat advisories\nGCC-CERT information sharing",
         r7="7.1", app="Both", typ="Detective", freq="Monthly",
         why="AI Ready7 Pillar 7 (Protection from AI Threats) had no corresponding RCM domain."),
    dict(domain="Protection from AI-Enabled Threats", id="AT-2", topic="AI-Augmented Detection & Automated Response",
         statement="The organisation shall enhance security operations with behaviour-based and AI-assisted detection and with automated response playbooks capable of containing machine-speed attacks, while maintaining human oversight of automated response actions and validating detection models for accuracy and drift.",
         refs="ISO42001:A.9.2\nNIST AI RMF:Manage 2.3 Manage 4.3\nSOC2:CC7.2 CC7.3 CC7.4",
         activities=["Deploy behavioural analytics (UEBA/XDR) covering users, systems and AI agents",
                     "Implement SOAR playbooks for AI-driven incidents (e.g., deepfake fraud, agent compromise, prompt-injection exfiltration)",
                     "Define human approval points for disruptive automated actions",
                     "Reduce vulnerability remediation cycles to days for exploitable critical vulnerabilities",
                     "Measure MTTD / MTTR and tune detection models"],
         evidence=["Detection use-case library including AI scenarios",
                   "SOAR playbooks and execution logs",
                   "Vulnerability remediation metrics",
                   "MTTD/MTTR reports"],
         tests=["Review detection coverage for AI-enabled attack scenarios",
                "Inspect playbook executions for human approval where required",
                "Verify critical-vulnerability remediation timelines",
                "Pass criterion: AI incident playbooks exercised at least annually"],
         iso="A.5.24, A.5.25, A.5.26, A.8.8, A.8.16", add="NIST CSF 2.0 (DE, RS)\nMITRE D3FEND",
         gcc="Bahrain NCSC standards\nCBB Rulebook OM Module - cyber security (licensees)",
         r7="7.2, 7.4", app="Both", typ="Detective", freq="Continuous",
         why="AI Ready7 items 7.2 and 7.4; no RCM control addressed defending against machine-speed AI-enabled attacks."),
    dict(domain="Protection from AI-Enabled Threats", id="AT-3", topic="Deepfake & Impersonation Resilience",
         statement="The organisation shall implement identity-verification and business-process controls resilient to deepfake voice/video and AI-enabled impersonation, including out-of-band verification for high-risk requests (e.g., payments, credential resets, data releases), liveness detection for remote identity proofing, and monitoring of human and non-human identities for anomalous behaviour.",
         refs="ISO42001:6.1.2\nNIST AI RMF:Manage 2.3\nSOC2:CC6.1 CC6.2",
         activities=["Mandate call-back / out-of-band verification for payment and sensitive change requests",
                     "Deploy liveness / injection-attack detection in remote onboarding (e-KYC)",
                     "Train staff with deepfake simulations (link GL-4)",
                     "Monitor for executive impersonation and brand-abuse deepfakes",
                     "Protect non-human identities and detect anomalous agent behaviour"],
         evidence=["Verification procedures for high-risk transactions",
                   "e-KYC liveness testing results",
                   "Deepfake simulation results",
                   "Impersonation monitoring reports"],
         tests=["Walk through a sample of high-value payment requests for out-of-band verification",
                "Review e-KYC vendor liveness test results (e.g., ISO/IEC 30107-3 PAD)",
                "Inspect deepfake simulation outcomes",
                "Pass criterion: 100% of sampled high-risk requests independently verified"],
         iso="A.5.16, A.5.17, A.6.3", add="ISO/IEC 30107-3 (presentation attack detection)\nFinCEN Alert FIN-2024-Alert004\nNIST SP 800-63-4 (digital identity guidelines)",
         gcc="CBB Rulebook - e-KYC / remote onboarding (licensees)\nBahrain Law No. 60 of 2014 on IT Crimes",
         r7="7.3, 3.3", app="Both", typ="Preventive", freq="Continuous; semi-annual simulations",
         why="AI Ready7 item 7.3 (GT Bahrain 'Some Met'); deepfake-enabled fraud is a material and fast-growing threat to GCC financial institutions."),
    dict(domain="Protection from AI-Enabled Threats", id="AT-4", topic="Continuous Adversarial Exposure Management",
         statement="The organisation shall continuously assess its exposure to AI-enabled adversaries through AI-specific red teaming, breach-and-attack simulation and exposure management across business systems and AI systems, prioritising remediation based on exploitability and business impact.",
         refs="ISO42001:9.1\nEU AI ACT:55.1a\nNIST AI RMF:Measure 2.7\nSOC2:CC4.1 CC7.1",
         activities=["Run AI-specific red-team exercises at least annually and for major releases",
                     "Use breach-and-attack simulation incorporating AI-enabled TTPs",
                     "Maintain an exposure-management programme (CTEM) with risk-based prioritisation",
                     "Track remediation to closure and re-test"],
         evidence=["Red-team reports and scopes",
                   "Attack-simulation results",
                   "Exposure-management dashboards",
                   "Remediation and re-test evidence"],
         tests=["Confirm red teaming performed within the last 12 months",
                "Trace critical findings to remediation and re-test",
                "Pass criterion: no critical finding open beyond agreed SLA"],
         iso="A.8.8, A.5.36", add="OWASP GenAI Red Teaming Guide (2025)\nMITRE ATLAS\nGartner CTEM model",
         gcc="Bahrain NCSC standards\nCBB cyber-resilience / penetration-testing requirements (licensees)",
         r7="7.5, 6.4", app="Both", typ="Detective", freq="Continuous; annual red team",
         why="AI Ready7 item 7.5; AA-3 covered validation of AI systems but not organisation-wide exposure to AI-enabled attackers."),
]

for c in NEW:
    c["activities_txt"] = _n(c["activities"])
    c["evidence_txt"] = _n(c["evidence"])
    c["tests_txt"] = _n(c["tests"])


# Regulatory & standards library ------------------------------------------------------------
# (name, issuer, jurisdiction, type, status_dates, relevance, rcm_controls)
LIBRARY = [
    ("EU Artificial Intelligence Act - Regulation (EU) 2024/1689", "European Union", "EU (extraterritorial)", "Binding law",
     "In force 1 Aug 2024. Prohibitions & AI literacy: 2 Feb 2025. GPAI obligations: 2 Aug 2025. Most obligations incl. Annex III high-risk & Art. 50 transparency: 2 Aug 2026. Annex I product-embedded high-risk: 2 Aug 2027. Digital Omnibus proposal (Nov 2025) may defer high-risk dates - confirm final adopted text.",
     "Applies to Bahrain entities placing AI on the EU market or whose AI output is used in the EU (e.g., banks with EU customers, exporters, multinationals).",
     "RO-1, RO-5, RO-6, RM-5, GL-4, LC-6, LC-7, CO-1, IM-2"),
    ("EU General-Purpose AI Code of Practice", "European Commission / AI Office", "EU", "Voluntary (presumption of conformity)",
     "Published July 2025 (Transparency, Copyright, Safety & Security chapters).", "Due diligence reference when selecting foundation-model providers.", "LC-6, LC-11"),
    ("ISO/IEC 42001:2023 - AI management system", "ISO/IEC JTC 1/SC 42", "International", "Certifiable standard",
     "Published Dec 2023. Certification available via accredited bodies (ISO/IEC 42006:2025).", "Primary management-system backbone of this RCM; basis for GT certification-readiness services.", "All domains"),
    ("ISO/IEC 23894:2023 - AI risk management guidance", "ISO/IEC", "International", "Guidance standard", "Published Feb 2023.", "Basis for the GT AI Risk Assessment Framework.", "RM-1 to RM-6"),
    ("ISO/IEC 42005:2025 - AI system impact assessment", "ISO/IEC", "International", "Guidance standard", "Published 2025.", "Method for use-case impact assessments / FRIA.", "RM-2, RO-6"),
    ("ISO/IEC 42006:2025 - Requirements for bodies auditing AIMS", "ISO/IEC", "International", "Requirements standard", "Published 2025.", "Audit and certification of ISO/IEC 42001.", "AA-1, AA-2"),
    ("ISO/IEC 5338:2023 - AI system life cycle processes", "ISO/IEC", "International", "Standard", "Published 2023.", "Lifecycle processes incl. retirement.", "LC-2, LC-5, LC-10"),
    ("ISO/IEC 22989:2022; ISO/IEC TR 24027:2021; ISO/IEC TR 24028:2020; ISO/IEC TR 24368:2022; ISO/IEC 25059:2023; ISO/IEC 5259 series", "ISO/IEC", "International", "Standards / technical reports",
     "Published.", "Terminology, bias (24027), trustworthiness (24028), ethics (24368), AI quality (25059), data quality (5259). Note: the GT service-line deck cites 'ISO/IEC TR 24028 for bias assessment' - the bias report is ISO/IEC TR 24027.", "LC-1, RS-3 to RS-6"),
    ("ISO/IEC 27001:2022 / 27002:2022", "ISO/IEC", "International", "Certifiable standard",
     "Transition from 2013 edition ended 31 Oct 2025. RCM Annex A references remapped to 2022 numbering in column I.", "Information-security baseline for AI systems.", "SE-1 to SE-7"),
    ("ISO/IEC 27701:2025", "ISO/IEC", "International", "Certifiable standard", "2025 edition issued as standalone PIMS; RCM clause references are to 2019 edition - remap at next review.", "Privacy management for AI processing personal data.", "PR-1 to PR-6"),
    ("NIST AI Risk Management Framework 1.0 (NIST AI 100-1) & Playbook", "NIST (US)", "International (voluntary)", "Voluntary framework", "Jan 2023.", "Govern / Map / Measure / Manage functions used across RCM.", "All domains"),
    ("NIST AI 600-1 - Generative AI Profile", "NIST (US)", "International (voluntary)", "Voluntary profile", "Jul 2024.", "12 GenAI risk categories and suggested actions.", "RM-1, LC-6, LC-7, OM-1"),
    ("NIST AI 100-2 E2025 - Adversarial ML taxonomy", "NIST (US)", "International (voluntary)", "Guidance", "Mar 2025.", "Attack taxonomy for AI security testing.", "SE-3, SE-6, AA-3"),
    ("OWASP Top 10 for LLM Applications 2025; OWASP Top 10 for Agentic Applications; OWASP GenAI Red Teaming Guide", "OWASP GenAI Security Project", "International", "Industry guidance", "2025.", "AI application security testing baseline.", "SE-6, SE-7, LC-8, AA-3"),
    ("MITRE ATLAS", "MITRE", "International", "Knowledge base", "Continuously updated.", "Adversary tactics & techniques against AI.", "SE-6, AT-1, AT-4"),
    ("ETSI TS 104 223 / EN 304 223 - Baseline cyber security requirements for AI; UK AI Cyber Security Code of Practice", "ETSI / UK DSIT", "International", "Standard / code of practice", "2025.", "Secure-by-design requirements across AI lifecycle.", "SE-1, SE-6, SE-7"),
    ("OECD AI Principles (updated 2024); UNESCO Recommendation on the Ethics of AI (2021); IEEE 7000 series; G7 Hiroshima Code of Conduct", "OECD / UNESCO / IEEE / G7", "International", "Principles", "Various.", "Ethical foundation referenced in GT service line.", "GL-1, GL-3, RS-*"),
    ("Council of Europe Framework Convention on AI (CETS No. 225)", "Council of Europe", "International treaty", "Treaty (upon ratification)", "Opened for signature Sep 2024.", "Human rights, democracy & rule-of-law impact assessment (HUDERIA).", "RM-2, RO-1"),
    ("Bahrain Personal Data Protection Law (Law No. 30 of 2018)", "Kingdom of Bahrain - Personal Data Protection Authority", "Bahrain", "Binding law",
     "In force Aug 2019.", "Lawful processing, sensitive data, data-subject rights, cross-border transfers and security of processing for AI using personal data.", "PR-1 to PR-6, SE-4"),
    ("General Policy for the Use of Artificial Intelligence v1.0", "Information & eGovernment Authority (iGA)", "Bahrain (government entities)", "Policy (non-binding for private sector)",
     "Issued 2025. Four pillars: commitment to policies & legislation; adoption & use; awareness & education; national & international cooperation.", "Primary national AI policy reference; signals regulatory direction.", "GL-1, GL-3, GL-4, GL-5, RO-5"),
    ("GCC Guiding Manual on the Ethics of Artificial Intelligence Use", "GCC General Secretariat (adopted by Bahrain iGA, 2025)", "GCC", "Ethical guidance", "Adopted 2025.", "Regional ethical principles (fairness, transparency, accountability, human oversight).", "RS-1 to RS-9, CO-1 to CO-3"),
    ("Draft AI Regulation Law (38 articles)", "Shura Council, Kingdom of Bahrain", "Bahrain", "Draft law", "Approved by Shura Council Apr 2024; under review by Council of Representatives - not in force.", "Would introduce an AI regulator, penalties and liability - monitor.", "RO-1, RO-5, RM-5"),
    ("Legislative Decree No. 56 of 2018 - cloud computing services to foreign parties; Law No. 60 of 2014 - IT crimes; Law No. 54 of 2018 - electronic communications & transactions; Law No. 22 of 2006 - copyright", "Kingdom of Bahrain", "Bahrain", "Binding law", "In force.", "Data hosting, cyber-crime (e.g., deepfake fraud), e-transactions and IP considerations for AI.", "PR-6, AT-3, LC-11"),
    ("CBB Rulebook (Volumes 1-7 and Common Volume) - HC, RM, OM (cyber security, outsourcing), BC modules", "Central Bank of Bahrain", "Bahrain (CBB licensees)", "Binding regulation",
     "In force; CBB has reviewed AI/ML use by licensees and introduced chatbot examination criteria. Confirm current AI-specific module references with CBB before client use.", "Governance, model use, outsourcing, cyber security and consumer protection for AI in financial services.", "GL-1, GL-2, RM-1, LC-9, TP-1 to TP-3, AT-3"),
    ("National Cyber Security Center (NCSC) standards & advisories", "NCSC Bahrain", "Bahrain", "Standards / advisories", "Ongoing.", "National cyber baseline for AI infrastructure.", "SE-1 to SE-7, AT-1 to AT-4"),
    ("UNESCO AI Readiness Assessment (RAM) Report - Kingdom of Bahrain", "UNESCO / iGA", "Bahrain", "Assessment report", "Nov 2025.", "National context for AI strategy (governance, data ecosystem, skills, inclusion).", "GL-3, RS-7"),
    ("SDAIA AI Ethics Principles (2023), Generative AI Guidelines (2024); KSA PDPL; NCA ECC-2:2024", "SDAIA / NCA (KSA)", "Saudi Arabia", "Principles / binding law", "In force.", "For clients operating in KSA.", "RO-5, PR-1, SE-1"),
    ("UAE Charter for the Development & Use of AI (2024); UAE PDPL (Decree-Law 45/2021); DIFC Regulation 10; CBUAE guidance on AI", "UAE authorities", "UAE", "Charter / binding law", "In force.", "For clients operating in UAE / DIFC.", "RO-5, LC-8, PR-1"),
    ("QCB Artificial Intelligence Guideline", "Qatar Central Bank", "Qatar", "Regulatory guideline", "Issued 2024.", "For financial clients operating in Qatar.", "RO-5, LC-9"),
    ("Korea AI Basic Act; Japan AI Promotion Act; China GenAI Interim Measures & AI-content labelling measures; Colorado AI Act (SB 24-205); NYC Local Law 144", "Various", "APAC / US", "Binding law", "Korea effective 22 Jan 2026; China labelling effective 1 Sep 2025; Colorado effective 30 Jun 2026.", "Relevant for multinational clients; informs global best practice.", "RO-5, RM-5, LC-7"),
    ("NSW AI Assessment Framework (AIAF) & Australian Guidance for AI Adoption", "Digital NSW / Australian Government", "Australia", "Government framework", "AIAF mandatory for NSW agencies (DCS-2024-04); assessment tool updated 2026.", "Model for risk-tiered self-assessment used in the GT AI Readiness Assessment Tool.", "RM-5, GL-7, GL-8, CO-3"),
    ("SR 11-7 (US Fed/OCC); PRA SS1/23 (UK) - model risk management", "US Fed/OCC; UK PRA", "US / UK", "Supervisory guidance", "SR 11-7 (2011); SS1/23 effective May 2024.", "Model risk management practice for financial-services AI.", "LC-9"),
]
