# -*- coding: utf-8 -*-
"""Question bank for the GT AI Readiness & Risk Assessment Tool (v2.0: 4 inherent-risk + 16 readiness questions, 5 domains)."""

PILLARS = ["Business Alignment", "Governance & Ethics", "Training & Development", "Data & Quality",
           "Architecture & Technology", "Protect AI Systems", "Protection from AI Threats"]

PILLAR_RISK = {
    "Business Alignment": "Poor AI direction leads to inconsistent use, unmanaged risk, duplication and weak accountability, slowing adoption and reducing trust.",
    "Governance & Ethics": "Weak AI governance (policies, guardrails, risk assessment, ownership) increases misuse, compliance breaches and uncontrolled AI sprawl.",
    "Training & Development": "Low AI literacy and skills increase unsafe use, susceptibility to AI-enabled threats, biased outcomes and limit effective adoption.",
    "Data & Quality": "Weak data governance and oversight increase the risk of breaches, bias, data misuse, lack of transparency and non-compliance.",
    "Architecture & Technology": "Weak AI architecture and controls increase security gaps, integration risk, undetected failures and unsustainable costs.",
    "Protect AI Systems": "Weak AI security practices increase the risk of unauthorised access, data leakage, vulnerable deployments and undetected misuse.",
    "Protection from AI Threats": "Weak AI-threat detection and response increase exposure to deepfakes, AI-crafted attacks and delayed response.",
}

AIAF_PRINCIPLES = ["Fairness", "Privacy & Security", "Transparency & Explainability", "Accountability",
                   "Human, Social & Environmental Wellbeing", "Human-Centred Values", "Reliability & Safety", "Contestability"]

# Part A - AI use & inherent risk profile (AIAF-derived). points 0-4 per option.
CONTEXT = [
    dict(id="A1", topic="AI use profile", weight=2,
         q="Which statement best describes how AI is used in your organisation today (including AI embedded in software and tools used by staff)?",
         guide="Consider approved and unapproved tools, vendor software with AI features and AI used by suppliers on your behalf.",
         opts=[("No AI in use and none planned within 12 months", "Minimal current AI exposure. Readiness still matters: governance is easier to establish before adoption."),
               ("Exploratory use of public GenAI tools (e.g., ChatGPT, Copilot web) for internal productivity only", "Main exposures are data leakage into public tools, inaccurate outputs and shadow AI. An acceptable-use policy and literacy training are the first priorities."),
               ("Approved enterprise GenAI tools and AI features embedded in business software across teams", "AI is part of day-to-day work. Exposure spans data protection, output quality, vendor dependence and consistent human review."),
               ("Custom or vendor-built AI / ML models supporting core processes or client services", "AI influences core outcomes. Model validation, monitoring, data governance and third-party assurance become essential."),
               ("AI agents or automated AI decisions acting directly on systems, customers or transactions", "Highest exposure profile: autonomous actions require execution limits, human approval points, kill-switches and continuous monitoring.")]),
    dict(id="A2", topic="Decision impact", weight=3,
         q="What is the most significant type of decision or outcome your AI systems influence?",
         guide="Answer for the highest-impact AI use case in scope (AIAF: 'worst credible harm').",
         opts=[("None - AI is used only for drafting, research or personal productivity", "No direct decisions about people; impact limited to quality of internal work products."),
               ("Internal operational decisions with minor impact (e.g., scheduling, document triage)", "Errors cause inconvenience but are easily corrected."),
               ("Customer- or client-facing outputs with limited individual impact (e.g., FAQ chatbots, marketing content)", "External stakeholders see AI outputs - disclosure, accuracy and reputational controls apply (e.g., EU AI Act Art. 50 where relevant)."),
               ("Decisions materially affecting individuals' services, employment or finances, with human review", "Fairness, explainability, contestability and effective human oversight are required; impact assessments recommended."),
               ("Decisions with legal or similarly significant effects on individuals (credit, hiring, insurance, eligibility, health) made or determined by AI", "Likely 'high-risk' AI (e.g., EU AI Act Annex III). Full impact assessment, independent validation and committee approval required.")]),
    dict(id="A3", topic="Data sensitivity", weight=2,
         q="What is the most sensitive data processed by your AI systems (including data staff enter into AI tools)?",
         guide="Include prompts, uploaded documents, training / fine-tuning data, retrieval sources and logs.",
         opts=[("Public or synthetic data only", "Low data-protection exposure."),
               ("Internal, non-confidential business information", "Low-moderate exposure; basic data-handling rules apply."),
               ("Confidential business or client information", "Confidentiality and contractual obligations apply; vendor data-use terms are critical."),
               ("Personal data of customers, employees or other individuals", "Bahrain PDPL applies: lawful basis, notice, DPIA, security, data-subject rights and cross-border transfer rules."),
               ("Sensitive personal data (health, biometric, financial account, children) or regulated / classified information", "Highest data exposure: strict minimisation, in-region hosting, enhanced security and privacy impact assessment required.")]),
    dict(id="A4", topic="Oversight & reversibility", weight=3,
         q="How much human oversight applies to AI outputs, and how reversible are the outcomes?",
         guide="AIAF considers autonomy, human oversight and whether outputs are reversible or correctable.",
         opts=[("Humans make all decisions; AI outputs are advisory drafts only", "Strong human control; residual risk mainly automation bias."),
               ("A qualified human reviews and approves every AI output before it is used", "Effective 'human-in-charge' control if reviewers are trained and have time and authority to challenge."),
               ("Humans review samples or exceptions; errors are easily corrected", "Partial oversight - sampling design, thresholds and monitoring determine effectiveness."),
               ("AI acts automatically; humans can intervene after the fact; errors are costly to reverse", "Limited oversight - requires guardrails, limits, monitoring and rapid rollback."),
               ("AI acts autonomously with no practical real-time intervention; outcomes may be irreversible", "Very high risk: strongest governance attention required before operation.")]),
]

LEVELS = ["Level 0 - Not in place", "Level 1 - Initial / ad hoc", "Level 2 - Defined", "Level 3 - Implemented", "Level 4 - Optimised"]

# Part B - readiness & control maturity. options scored 0/25/50/75/100
READINESS = [
    dict(id="Q5", pillar="Business Alignment", topic="AI strategy, ownership & risk appetite", r7="1.1", rcm="GL-1, GL-3, RM-6", type="☆ Recommended",
         principles=["Accountability"],
         q="Is there executive ownership and an approved AI strategy that defines the ambition, where AI will be used and the organisation's AI risk appetite?",
         guide="Evidence: approved AI strategy, named executive sponsor, risk appetite statement, experimentation boundaries.",
         opts=["No AI strategy or executive owner; AI adoption is unplanned",
               "Informal interest from leadership; no documented strategy or risk appetite",
               "Executive sponsor named and AI strategy drafted or approved, but risk appetite and experimentation boundaries not defined",
               "Approved AI strategy with executive ownership, defined risk appetite and experimentation boundaries communicated to staff",
               "Strategy and appetite reviewed at least annually by board / executive, linked to business strategy and tracked through KPIs and KRIs"],
         risk="Lack of executive direction leads to inconsistent AI use, unmanaged risk-taking, poor-quality outputs and fragmented adoption.",
         recs=["Appoint an executive AI sponsor and commission an AI strategy (situational / SWOT analysis, ambition, priority domains, risk appetite).",
               "Formalise leadership intent into a documented AI strategy approved by the executive committee, with a board-approved AI risk appetite.",
               "Define AI risk appetite, tolerances and approved experimentation ('sandbox') boundaries; communicate them organisation-wide.",
               "Link the strategy to measurable KPIs / KRIs and introduce an annual board-level review of AI strategy and risk appetite.",
               "Sustain: benchmark annually against peers and refresh strategy as AI capabilities and regulation evolve."]),
    dict(id="Q6", pillar="Business Alignment", topic="Use-case portfolio & value realisation", r7="1.2, 1.3", rcm="GL-6, GL-5", type="☆ Recommended",
         principles=["Human, Social & Environmental Wellbeing"],
         q="How are AI use cases identified, prioritised, approved and measured for value?",
         guide="Evidence: intake form, prioritisation criteria, business cases, benefit KPIs, portfolio reviews.",
         opts=["No process - AI initiatives start ad hoc and value is not tracked",
               "Some use cases discussed informally; business cases are rare",
               "Use-case intake exists and initiatives are prioritised, but benefits are not systematically tracked",
               "Structured intake and prioritisation by value, feasibility, data readiness and risk; KPIs tracked for major initiatives",
               "Portfolio managed as a whole with quarterly value / risk reviews, stop-or-scale decisions, and shadow-AI demand routed into the governed pipeline"],
         risk="Duplicated or low-value AI investment, shadow AI and inability to demonstrate return on investment.",
         recs=["Create an AI use-case intake and approval process; build an initial prioritised backlog.",
               "Introduce a standard business-case template with value, feasibility, data-readiness and risk scoring.",
               "Define benefit KPIs (financial and non-financial) at approval and assign benefit owners.",
               "Run quarterly portfolio reviews with continue / pivot / stop decisions; convert discovered shadow AI into governed use cases.",
               "Sustain: publish realised value to leadership and reinvest in proven use cases."]),
    dict(id="Q7", pillar="Governance & Ethics", topic="AI policy, acceptable use & regulatory compliance", r7="2.1, 2.2", rcm="GL-5, RO-1, RO-5", type="⟳ Compliance Obligation",
         principles=["Accountability", "Privacy & Security"],
         q="Do you have an approved AI (acceptable-use) policy and a process to identify and comply with applicable AI-related regulation (e.g., Bahrain PDPL, CBB rules, EU AI Act)?",
         guide="Evidence: AI policy, approved-tools list, staff acknowledgements, obligations register, compliance reviews.",
         opts=["No AI policy; applicable AI regulations have not been identified",
               "Informal guidance only (e.g., emails); obligations understood by a few individuals",
               "AI acceptable-use policy approved; regulatory obligations identified but not mapped to controls",
               "AI policy enforced with staff acknowledgement; obligations register maps regulations to controls and owners",
               "Policy and obligations register reviewed regularly with horizon scanning; compliance tested and audit-ready evidence maintained"],
         risk="Misuse of AI, data leakage and breach of legal or regulatory requirements, with exposure to penalties, licence conditions and reputational harm.",
         recs=["Issue an interim AI acceptable-use policy immediately (approved tools, prohibited data, output verification) and identify applicable regulations.",
               "Approve a formal AI policy; build an AI obligations register covering Bahrain PDPL, sector rules (e.g., CBB) and extraterritorial regimes (EU AI Act).",
               "Map each obligation to controls and owners using the GT AI RCM; require annual staff acknowledgement.",
               "Establish monthly regulatory horizon scanning and periodic compliance testing with evidence retention.",
               "Sustain: keep audit-ready evidence packs and consider ISO/IEC 42001 certification."]),
    dict(id="Q8", pillar="Governance & Ethics", topic="AI inventory & risk / impact assessment", r7="2.4, 2.5", rcm="GL-8, RM-2, RM-5, TP-2", type="⚠ Mandatory Requirement",
         principles=["Accountability", "Human, Social & Environmental Wellbeing"],
         q="Do you maintain an inventory of AI systems with named owners, and assess AI risks and impacts (including third-party AI) before and after deployment?",
         guide="Evidence: AI register, risk-tiering records, impact assessments, vendor AI due diligence, re-assessment records.",
         opts=["No inventory; AI risks are not assessed",
               "Partial list of AI tools; risks assessed occasionally through general IT or vendor processes",
               "AI register with owners; risk assessments performed for some AI systems using a documented method",
               "Complete AI register; all AI use cases risk-tiered and assessed (incl. third-party AI) with approvals proportionate to risk",
               "Register reconciled quarterly; impact assessments (ISO/IEC 42005 / FRIA) for high-risk uses; re-assessment on change with KRIs monitored"],
         risk="Deployment of vulnerable, non-compliant or harmful AI systems and unknown AI exposure across the organisation and its supply chain.",
         recs=["Build an AI register (discover all AI incl. embedded and shadow AI) and assign business and technical owners.",
               "Adopt the GT AI Risk Assessment Framework: prohibited-practice screening and inherent-risk tiering for every AI use case.",
               "Extend assessments to all AI systems and third-party AI; set approval authority by risk tier.",
               "Introduce ISO/IEC 42005-style impact assessments for High / Critical tiers and quarterly register reconciliation.",
               "Sustain: automate KRI monitoring and trigger-based re-assessment."]),
    dict(id="Q9", pillar="Governance & Ethics", topic="Responsible-AI guardrails & human oversight", r7="2.3, 5.2", rcm="GL-7, RS-1, RS-4, RS-5, CO-1, CO-3", type="⚖ Ethical Consideration",
         principles=["Fairness", "Transparency & Explainability", "Human-Centred Values", "Contestability"],
         q="Are there practical guardrails for fairness, transparency and human oversight, overseen by an AI committee or centre of excellence?",
         guide="Evidence: committee / CoE charter, guardrail standards, human-in-charge procedures, bias tests, AI disclosures, appeal routes.",
         opts=["No responsible-AI guardrails or oversight body",
               "High-level ethical principles published but not operationalised",
               "AI committee / CoE established; guardrails defined for some areas (e.g., human review of outputs)",
               "Guardrails for fairness, transparency, disclosure and human-in-charge controls applied to all relevant AI; committee approves high-risk uses",
               "Guardrails tested (bias testing, oversight effectiveness); contestability routes for affected persons; lessons fed back into standards"],
         risk="Biased or harmful outcomes, undisclosed AI use and lack of accountability for AI-supported decisions.",
         recs=["Establish an AI committee / centre of excellence with a charter and decision rights.",
               "Translate ethical principles (GCC AI Ethics Manual, OECD) into practical guardrails: permitted uses, disclosure, human review, bias checks.",
               "Apply mandatory human-in-charge controls and AI disclosure to all relevant AI; require committee approval for High / Critical uses.",
               "Test guardrail effectiveness (bias testing, oversight reviews) and provide contest / appeal routes for affected persons.",
               "Sustain: publish a responsible-AI statement and report guardrail performance to the board."]),
    dict(id="Q10", pillar="Training & Development", topic="AI literacy & capability", r7="3.1, 3.2, 3.3, 3.4", rcm="GL-4, RS-9", type="⟳ Compliance Obligation",
         principles=["Human-Centred Values"],
         q="Have staff received AI literacy training appropriate to their role, and are specialist AI, governance and security skills being developed?",
         guide="Evidence: training curricula, completion records, role-based pathways, deepfake / phishing simulations, workforce plan.",
         opts=["No AI training provided",
               "Ad hoc awareness sessions or self-learning only",
               "Baseline AI literacy training available to all staff; limited role-based training",
               "Mandatory AI literacy before tool access; role-based pathways for developers, oversight staff and leaders; scenario-based security awareness",
               "Competence measured and refreshed annually; workforce plan addresses future AI skills and job redesign; active AI champions network"],
         risk="Unsafe use, susceptibility to AI-enabled threats and poor adoption; non-compliance with the EU AI Act Art. 4 AI-literacy duty where applicable.",
         recs=["Launch baseline AI literacy (safe use, limitations, data handling, verification) for all staff.",
               "Make AI literacy mandatory before AI tool access and track completion.",
               "Add role-based pathways (developers, oversight staff, leaders, risk & audit) and hands-on labs.",
               "Measure competence, refresh annually, and build an AI champions network and workforce plan.",
               "Sustain: integrate AI capability into performance frameworks and succession planning."]),
    dict(id="Q11", pillar="Data & Quality", topic="Data governance, quality & privacy for AI", r7="5.1, 5.3, 5.4, 5.5", rcm="LC-1, SE-4, PR-1, PR-4, PR-5, PR-6", type="⟳ Compliance Obligation",
         principles=["Privacy & Security", "Fairness"],
         q="Is data used by AI classified, quality-assured, traceable and protected in line with privacy requirements (e.g., Bahrain PDPL)?",
         guide="Evidence: data classification applied to AI, data-readiness assessments, lineage, DPIAs, redaction / anonymisation, transfer assessments.",
         opts=["Data used by AI is not classified or controlled; privacy requirements not considered",
               "Data classification policy exists but is not applied to AI; privacy reviewed case by case",
               "Classification and handling rules apply to AI; DPIAs performed for some AI using personal data",
               "Data readiness assessed before approval; lineage and quality monitored; minimisation, anonymisation and prompt redaction applied; DPIAs standard",
               "Automated quality, lineage and privacy controls across AI pipelines; data-subject rights and cross-border transfers handled for AI systems"],
         risk="Data breaches, PDPL non-compliance, and biased or inaccurate outputs from poor-quality or unsuitable data.",
         recs=["Prohibit confidential / personal data in unapproved AI tools and apply data classification to AI use immediately.",
               "Embed DPIAs for AI processing personal data and enforce classification-based handling rules (DLP).",
               "Require data-readiness assessments before approving use cases; implement minimisation, anonymisation and prompt redaction.",
               "Automate data-quality and lineage monitoring; operationalise data-subject rights and transfer assessments for AI.",
               "Sustain: continuous data-quality KPIs and periodic privacy audits of AI systems."]),
    dict(id="Q12", pillar="Architecture & Technology", topic="AI architecture, integration & monitoring", r7="4.1, 4.2, 4.3, 4.4, 4.5", rcm="LC-2, LC-3, LC-8, LC-12, OM-1, OM-4, RM-6", type="☆ Recommended",
         principles=["Reliability & Safety"],
         q="Is there a common AI reference architecture with standard integration patterns, and are AI systems monitored for performance, drift and cost?",
         guide="Evidence: reference architecture, approved platforms, integration / agent patterns, monitoring dashboards, cost reports.",
         opts=["No architectural standards; AI solutions built or bought in isolation",
               "Some technical guidance exists; monitoring limited to availability",
               "Reference architecture drafted; approved platforms and integration patterns for most AI; basic performance monitoring",
               "Reference architecture adopted (data, models, agents, security); agent actions via a policy-enforcement gateway; performance, drift and bias monitored with thresholds; kill switches; cost governed",
               "Full observability with KRIs and automated responses; governed path from citizen-developed AI to production; platform and vendor dependencies actively managed"],
         risk="Inconsistent and insecure implementations, undetected model drift or failure, excessive agent privileges and unsustainable AI costs.",
         recs=["Define approved AI platforms and a minimum architecture standard (identity, data, logging) for all AI solutions.",
               "Develop an enterprise AI reference architecture covering data, models, agents, integration and security.",
               "Centralise API / access control for AI, define agent execution authority and implement drift / performance monitoring with thresholds.",
               "Implement KRI-based observability with automated responses and a governed pathway from citizen development to production.",
               "Sustain: review architecture annually against emerging AI capabilities and vendor landscape."]),
    dict(id="Q13", pillar="Protect AI Systems", topic="Securing AI systems", r7="6.1, 6.2, 6.3, 6.4, 6.5", rcm="SE-2, SE-3, SE-6 to SE-10, OM-2, AA-3", type="⚠ Mandatory Requirement",
         principles=["Privacy & Security", "Reliability & Safety"],
         q="Are AI systems protected with least-privilege access, secure development and testing (incl. red teaming for prompt injection), and runtime logging?",
         guide="Evidence: AI threat models, access reviews (incl. agent identities), AI red-team reports, guardrail and sandbox configurations, audit logs. Detailed test: GT AI Security & Agent Audit Checklist.",
         opts=["AI systems are not specifically considered in security controls",
               "Standard IT security controls apply; no AI-specific threat assessment",
               "AI-specific threats (e.g., prompt injection, data leakage) assessed for some systems; access controls and logging in place",
               "Secure AI development lifecycle; least privilege for users, systems and agents; sandboxed tool execution; AI red teaming before release; runtime guardrails and audit logging",
               "Continuous adversarial testing, AI supply-chain assurance (model scanning, AI-BOM) and forensic-ready logging integrated with the SOC"],
         risk="Unauthorised access, model compromise, data exfiltration through AI and undetected misuse.",
         recs=["Perform AI threat modelling (OWASP LLM Top 10) on existing AI systems and close critical exposures.",
               "Extend secure-development and access-management standards to AI, including non-human (agent) identities.",
               "Introduce AI red teaming before release, runtime guardrails (input / output filtering) and audit logging.",
               "Add AI supply-chain controls (model scanning, AI-BOM) and continuous adversarial testing integrated with the SOC.",
               "Sustain: track AI security KRIs and re-test after every material model or provider change."]),
    dict(id="Q14", pillar="Protection from AI Threats", topic="Defending against AI-enabled threats", r7="7.1, 7.2, 7.3, 7.4, 7.5", rcm="AT-1, AT-2, AT-3, AT-4", type="☆ Recommended",
         principles=["Privacy & Security"],
         q="Is the organisation prepared for AI-enabled attacks such as deepfake impersonation, AI-crafted phishing and automated exploitation?",
         guide="Evidence: AI threat intelligence, out-of-band verification procedures, deepfake simulations, SOC use cases, playbooks, patch metrics.",
         opts=["AI-enabled threats not considered",
               "General awareness only; no specific controls",
               "Threat intelligence covers AI-enabled attacks; out-of-band verification for some high-risk requests",
               "Deepfake-resilient verification for payments and sensitive requests; behaviour-based detection; AI incident playbooks exercised",
               "Continuous exposure management and AI-specific red teaming; automated response at machine speed; critical vulnerabilities remediated in days"],
         risk="Deepfake-enabled fraud, account compromise and faster, more scalable attacks that outpace defences.",
         recs=["Introduce mandatory call-back / out-of-band verification for payments and sensitive requests.",
               "Add AI-enabled attack scenarios to threat intelligence, awareness and phishing simulations.",
               "Deploy behaviour-based detection and exercise AI incident playbooks (deepfake fraud, agent compromise).",
               "Adopt continuous exposure management and AI-specific red teaming; reduce patch cycles to days.",
               "Sustain: share AI threat intelligence with sector peers and national CERT."]),
    dict(id="Q15", pillar="Governance & Ethics", topic="AI incidents, monitoring & assurance", r7="2.2, 7.4", rcm="IM-1, IM-2, IM-3, AA-1, AA-2, RO-4", type="⟳ Compliance Obligation",
         principles=["Accountability", "Reliability & Safety", "Contestability", "Transparency & Explainability"],
         q="Are AI incidents detected, managed and reported, and is AI governance subject to internal audit or independent assurance?",
         guide="Evidence: AI incident categories, notification criteria, incident logs, internal-audit reports, vendor assurance, certification status.",
         opts=["No AI incident process or assurance",
               "AI issues handled through general IT incident processes; no AI-specific assurance",
               "AI incident categories and escalation defined; ad hoc reviews of AI controls",
               "AI incident management with regulatory notification criteria; periodic internal audit of AI governance; assurance obtained from AI vendors",
               "Post-incident learning drives improvement; AI management system certified or certification-ready (ISO/IEC 42001); assurance reported to the board"],
         risk="Delayed response to AI failures, missed regulatory notifications and lack of defensible evidence for regulators, auditors and clients.",
         recs=["Define AI incident categories, severity and escalation within the existing incident process.",
               "Add regulatory notification criteria (PDPL, CBB, EU AI Act Art. 73 where applicable) and AI incident logging.",
               "Include AI governance in the internal-audit plan and obtain assurance evidence from AI vendors.",
               "Implement post-incident learning and an ISO/IEC 42001 certification-readiness review.",
               "Sustain: maintain certification and report AI assurance results to the board annually."]),
]

EXPOSURE = {  # (inherent tier, maturity band) -> exposure
    ("Low", "Adaptive"): "Low", ("Low", "Repeatable"): "Low", ("Low", "Informed"): "Moderate", ("Low", "Partial"): "Moderate",
    ("Medium", "Adaptive"): "Low", ("Medium", "Repeatable"): "Moderate", ("Medium", "Informed"): "Moderate", ("Medium", "Partial"): "High",
    ("High", "Adaptive"): "Moderate", ("High", "Repeatable"): "Moderate", ("High", "Informed"): "High", ("High", "Partial"): "Critical",
    ("Critical", "Adaptive"): "Moderate", ("Critical", "Repeatable"): "High", ("Critical", "Informed"): "Critical", ("Critical", "Partial"): "Critical",
}
PATHWAY = [
    ("Low", "PROCEED - SELF-MANAGED", "AI capability is broadly commensurate with the organisation's AI risk profile. Maintain controls, keep the AI register current and reassess annually or on material change."),
    ("Moderate", "PROCEED WITH CONDITIONS", "Continue AI adoption, but address the identified gaps through a time-bound remediation plan (within 90 days for priority items). Obtain SME review (risk, privacy, security) for new AI use cases."),
    ("High", "REMEDIATE BEFORE SCALING", "Readiness is insufficient for the organisation's AI risk profile. Limit AI to lower-risk uses until priority gaps are closed; place AI adoption under AI committee / executive oversight."),
    ("Critical", "PAUSE HIGH-IMPACT AI & ESCALATE", "Significant AI exposure with immature controls. Escalate to the board / executive committee; do not deploy or expand high-impact AI until critical controls are in place."),
]
MATURITY = [("Partial", 0, "Foundational capabilities are missing or ad hoc; AI risk is largely unmanaged."),
            ("Informed", 0.5, "Awareness and some defined practices exist, but they are not consistently implemented."),
            ("Repeatable", 0.7, "Practices are defined and consistently applied across most of the organisation."),
            ("Adaptive", 0.9, "Practices are optimised, measured and continuously improved.")]

SERVICES = [
    ("AI Governance, Risk & Compliance", "Governance & Ethics", "AI governance framework & policies, AI register, risk & impact assessments (GT AI Risk Assessment Framework), RCM-based compliance reviews, ISO/IEC 42001 readiness."),
    ("AI Strategy & Roadmap", "Business Alignment", "Situational / SWOT analysis, AI strategy and risk appetite, use-case prioritisation, value-realisation KPIs and phased roadmap."),
    ("Training & Awareness", "Training & Development", "AI literacy programmes, role-based pathways, immersive labs, deepfake & AI-phishing simulations, leadership workshops."),
    ("AI-Driven Automation & Architecture", "Architecture & Technology", "Technology evaluation and selection, reference architecture, AI integration and monitoring. GT AI apps in preparation: AI-powered Business Continuity (BCP) tool and AI-powered Financial Statements tool."),
    ("AI Security & Cyber Resilience", "Protect AI Systems", "AI security audits (GT AI Security & Agent Audit Checklist), AI red teaming, secure AI agents (ISACA 2026 baseline), deepfake-resilient processes."),
]


# =====================================================================================
# v2.0 (Oct 2026): 20 questions, 5 domains, 5 new governance & risk-management questions
# =====================================================================================
DOMAIN_MAP = {"Business Alignment": "Strategy & Value", "Governance & Ethics": "Governance, Risk & Compliance",
              "Training & Development": "People & Skills", "Data & Quality": "Data & Technology",
              "Architecture & Technology": "Data & Technology", "Protect AI Systems": "AI Security & Threat Risk",
              "Protection from AI Threats": "AI Security & Threat Risk"}
PILLARS = ["Strategy & Value", "Governance, Risk & Compliance", "People & Skills", "Data & Technology", "AI Security & Threat Risk"]
READY7_SOURCE = {"Strategy & Value": "Business Alignment", "Governance, Risk & Compliance": "Governance & Ethics",
                 "People & Skills": "Training & Development", "Data & Technology": "Data & Quality + Architecture & Technology",
                 "AI Security & Threat Risk": "Protect AI Systems + Protection from AI Threats"}
PILLAR_RISK = {
    "Strategy & Value": "Without clear direction, ownership and value tracking, AI adoption is fragmented, duplicated and hard to justify, and risk-taking is unmanaged.",
    "Governance, Risk & Compliance": "Weak AI governance, risk management and compliance increase misuse, regulatory breaches, unmanaged third-party exposure and uncontrolled AI sprawl.",
    "People & Skills": "Low AI literacy and specialist capability increase unsafe use, susceptibility to AI-enabled threats and biased or unchecked outputs.",
    "Data & Technology": "Weak data governance, architecture and model validation lead to inaccurate or biased outputs, privacy breaches, undetected drift and unsustainable costs.",
    "AI Security & Threat Risk": "Weak AI security and threat defences expose the organisation to prompt injection, data leakage, model compromise and deepfake-enabled fraud.",
}
_old = {q["id"]: q for q in READINESS}
for _q in READINESS:
    _q["pillar"] = DOMAIN_MAP[_q["pillar"]]
_old["Q5"].update(topic="AI strategy & executive ownership", rcm="GL-1, GL-3",
    q="Is there executive ownership and an approved AI strategy that defines the ambition, priorities and where AI will (and will not) be used?",
    guide="Evidence: approved AI strategy, named executive sponsor, AI budget, communicated priorities and experimentation boundaries.",
    opts=["No AI strategy or executive owner; AI adoption is unplanned",
          "Informal leadership interest; no documented strategy",
          "Executive sponsor named and AI strategy drafted, but not linked to business objectives or budget",
          "Approved AI strategy with executive ownership, priorities, budget and experimentation boundaries communicated to staff",
          "Strategy reviewed at least annually by the board, linked to business strategy and tracked through KPIs"],
    recs=["Appoint an executive AI sponsor and commission an AI strategy (situational / SWOT analysis, ambition, priority domains).",
          "Formalise leadership intent into a documented AI strategy approved by the executive committee.",
          "Link the strategy to business objectives and budget; define experimentation ('sandbox') boundaries and communicate them.",
          "Track the strategy through KPIs and introduce an annual board-level review.",
          "Sustain: benchmark annually against peers and refresh the strategy as AI capabilities and regulation evolve."])

NEWQ = {
 "G1": dict(pillar="Governance, Risk & Compliance", topic="AI governance structure & accountability", r7="1.1, 2.3", rcm="GL-1, GL-2, GL-7, AA-1", type="⚠ Mandatory Requirement",
    principles=["Accountability"],
    q="Is there a defined AI governance structure - board / executive oversight, an AI committee with decision rights, named owners for every AI system and clear three-lines-of-defence responsibilities?",
    guide="Evidence: board / ExCo terms of reference covering AI, AI committee charter, RACI, AI system owner register, internal-audit coverage.",
    opts=["No defined AI governance; decisions are made ad hoc by individual teams",
          "Informal oversight by IT or a single function; roles not documented",
          "AI committee or sponsor defined on paper; roles and decision rights partly documented",
          "Board / ExCo oversight, AI committee with charter and decision rights, named system owners and a documented RACI across the three lines",
          "Governance operates effectively: regular board reporting, periodic effectiveness review and independent assurance by internal audit"],
    risk="Unclear accountability for AI decisions and outcomes, inconsistent approvals and no escalation route when AI fails.",
    recs=["Appoint an executive AI owner and agree who decides on AI use cases; document interim responsibilities.",
          "Establish an AI committee / centre of excellence with a charter, decision rights and members from business, risk, legal, privacy and IT.",
          "Assign named business and technical owners to every AI system and publish a RACI across the three lines of defence.",
          "Introduce regular board / ExCo AI reporting and an annual governance-effectiveness review by internal audit.",
          "Sustain: benchmark governance against ISO/IEC 42001 and refresh roles as AI use evolves."]),
 "G2": dict(pillar="Governance, Risk & Compliance", topic="AI risk management framework", r7="2.4", rcm="RM-1, RM-2, RM-3, RM-5", type="⚠ Mandatory Requirement",
    principles=["Accountability", "Reliability & Safety"],
    q="Is there a documented AI risk management framework - risk taxonomy, assessment method, scoring scales and treatment process - integrated with enterprise risk management?",
    guide="Evidence: AI risk framework / methodology (e.g., aligned to ISO/IEC 23894 or NIST AI RMF), AI risk register, link to the enterprise risk register, completed assessments.",
    opts=["AI risks are not identified or managed",
          "AI risks considered informally within general IT or project risk",
          "AI risk methodology drafted (taxonomy, scales) and applied to some AI initiatives",
          "Approved AI risk framework aligned to ISO/IEC 23894 / NIST AI RMF, applied to all AI use cases and integrated with the enterprise risk register",
          "Framework reviewed annually; AI risk aggregated across the portfolio and used in decisions; treatment effectiveness tested"],
    risk="AI risks go unidentified or are rated inconsistently, so high-risk AI is approved without proportionate controls.",
    recs=["Adopt an AI risk management framework (e.g., GT AI Risk Assessment Framework) with a risk taxonomy and scoring scales.",
          "Formalise the methodology, approve it at executive level and pilot it on current AI initiatives.",
          "Apply the framework to every AI use case, record results in an AI risk register and integrate it with enterprise risk management.",
          "Aggregate AI risk across the portfolio, review the framework annually and test the effectiveness of treatments.",
          "Sustain: align with ISO/IEC 42001 clause 6.1 and refresh the taxonomy for new threats (e.g., agentic AI)."]),
 "G3": dict(pillar="Governance, Risk & Compliance", topic="AI risk appetite, KRIs & reporting", r7="1.1, 4.4", rcm="RM-6, RM-4, GL-1", type="⚠ Mandatory Requirement",
    principles=["Accountability"],
    q="Has the board approved an AI risk appetite with measurable tolerances, and are key risk indicators (KRIs) monitored and reported with defined escalation?",
    guide="Evidence: approved AI risk appetite statement, KRI library with thresholds, risk dashboards, escalation and breach records.",
    opts=["No AI risk appetite or risk indicators",
          "Enterprise risk appetite exists but does not address AI",
          "AI risk appetite drafted; a few indicators tracked informally",
          "Board-approved AI risk appetite with tolerances; KRIs with thresholds monitored and reported at least quarterly",
          "KRIs automated with mandatory responses on breach; appetite reviewed annually and used to steer investment and approvals"],
    risk="No shared view of how much AI risk is acceptable - leading to reckless adoption or blocked innovation - and late detection of deteriorating AI risk.",
    recs=["Define the AI risk categories that matter most (e.g., client data, compliance, output quality) and agree an initial position.",
          "Draft an AI risk appetite statement with measurable tolerances and obtain board approval.",
          "Define KRIs with thresholds and escalation for each risk category and report them to the AI committee quarterly.",
          "Automate KRI collection and define mandatory responses (e.g., suspend, human review, rollback) when thresholds are breached.",
          "Sustain: review the appetite annually and use it to steer AI investment and approval decisions."]),
 "G4": dict(pillar="Governance, Risk & Compliance", topic="Third-party & AI supply-chain risk", r7="2.4, 6.2", rcm="TP-1, TP-2, TP-3, SE-7, LC-6", type="⟳ Compliance Obligation",
    principles=["Privacy & Security", "Accountability"],
    q="Are AI vendors, AI features in purchased software and foundation-model providers risk-assessed before use, with AI-specific contract clauses and ongoing monitoring?",
    guide="Evidence: AI vendor due-diligence questionnaire, contract clauses (no training on your data, residency, incident notice, audit rights), vendor assurance (ISO/IEC 42001, SOC 2), review records.",
    opts=["AI vendors and AI features in software are not assessed",
          "Standard IT procurement only; AI-specific risks not considered",
          "AI questions added to vendor due diligence for some purchases; contract terms vary",
          "Mandatory AI due diligence and standard AI contract clauses for all AI vendors; providers reviewed annually",
          "Continuous monitoring of AI vendors and model changes; AI bill of materials maintained; exit plans for critical providers"],
    risk="Client or personal data used to train vendor models, unmanaged model changes, concentration on a single provider and regulatory breaches through suppliers.",
    recs=["Identify all AI vendors and AI features in existing software; stop use of unvetted tools with confidential data.",
          "Add AI-specific questions to vendor due diligence (data use, hosting, model changes, security, certifications).",
          "Make AI due diligence mandatory and adopt standard AI contract clauses (no training on client data, residency, audit, incident notice).",
          "Monitor AI vendors continuously, maintain an AI bill of materials and define exit plans for critical providers.",
          "Sustain: re-assess providers on material model or ownership changes and share findings with procurement."]),
 "G5": dict(pillar="Data & Technology", topic="Model risk management & validation", r7="4.4, 6.3", rcm="LC-9, RS-6, LC-13, OM-1", type="☆ Recommended",
    principles=["Reliability & Safety", "Fairness"],
    q="Are material AI / ML models independently validated before use and periodically, with a model inventory, performance thresholds and documented limitations?",
    guide="Evidence: model risk policy, model inventory with risk tiers, independent validation reports, performance monitoring, validation-findings tracker.",
    opts=["Models are not validated or inventoried",
          "Developers test their own models; no independent review",
          "Model inventory exists; validation performed for some material models",
          "Independent validation before use and on a risk-based cycle; performance thresholds and limitations documented",
          "Model risk management aligned to SR 11-7 / PRA SS1/23 principles, with continuous monitoring and findings tracked to closure"],
    risk="Inaccurate, biased or unstable models drive decisions unnoticed, with regulatory exposure for financial-services clients.",
    recs=["Create an inventory of AI / ML models and identify those that drive material decisions.",
          "Introduce a model risk policy and require independent review (separate from developers) for material models.",
          "Validate all material models before use and on a risk-based cycle; document thresholds, limitations and conditions of use.",
          "Monitor model performance continuously and track validation findings to closure.",
          "Sustain: align with SR 11-7 / PRA SS1/23 principles and report model risk to the risk committee."]),
}
_order = [("Q5", _old["Q5"]), ("Q6", _old["Q6"]),
          ("Q7", NEWQ["G1"]), ("Q8", _old["Q7"]), ("Q9", NEWQ["G2"]), ("Q10", NEWQ["G3"]), ("Q11", _old["Q8"]),
          ("Q12", NEWQ["G4"]), ("Q13", _old["Q9"]), ("Q14", _old["Q15"]),
          ("Q15", _old["Q10"]),
          ("Q16", _old["Q11"]), ("Q17", _old["Q12"]), ("Q18", NEWQ["G5"]),
          ("Q19", _old["Q13"]), ("Q20", _old["Q14"])]
READINESS = []
for _id, _q in _order:
    _q = dict(_q); _q["id"] = _id; READINESS.append(_q)
_old["Q9"]["topic"] = "Responsible-AI guardrails & human oversight"

SERVICES = [
    ("AI Governance, Risk & Compliance", "Governance, Risk & Compliance", "AI governance structure and policies, AI risk management framework and risk appetite, AI register, third-party AI risk, RCM-based compliance reviews, ISO/IEC 42001 readiness."),
    ("AI Strategy & Roadmap", "Strategy & Value", "AI Opportunity Discovery (where AI and automation fit), AI strategy, use-case prioritisation, value-realisation KPIs and phased roadmap."),
    ("Training & Awareness", "People & Skills", "AI literacy programmes, role-based pathways, immersive labs, deepfake & AI-phishing simulations, board AI governance sessions."),
    ("AI-Driven Automation & Data", "Data & Technology", "Technology evaluation, data readiness, reference architecture, model validation and integration. GT AI apps in preparation: AI-powered BCP tool and AI-powered Financial Statements tool."),
    ("AI Security & Cyber Resilience", "AI Security & Threat Risk", "AI security audits (GT AI Security & Agent Audit Checklist), AI red teaming, secure AI agents, deepfake-resilient processes."),
]

# Profile questions for the client questionnaire; 'label' must equal the engine's '1. Profile' column-B label
SECTORS = ["Banking & financial services", "Insurance", "Government & public sector", "Telecommunications", "Healthcare", "Hospitality & tourism",
           "Professional services", "Manufacturing & industry", "Retail & consumer", "Energy & utilities", "Education", "Other"]
SIZES = ["1-50 employees", "51-250 employees", "251-1,000 employees", "1,001-5,000 employees", "More than 5,000 employees"]
SCOPES = ["Whole organisation", "Business unit / function", "Specific AI system or use case"]
ROLES = ["Deployer only (uses AI built by others)", "Provider (develops / sells AI systems)", "Both provider and deployer"]
YN = ["Yes", "No"]
PROFILE_Q = [
    ("P1", "Organisation name", "Organisation name", None),
    ("P2", "Sector", "Sector", SECTORS),
    ("P3", "Organisation size", "Organisation size", SIZES),
    ("P4", "Scope of this assessment", "Scope of assessment", SCOPES),
    ("P5", "Scope description (optional)", "Scope description (optional)", None),
    ("P6", "Your name", "Completed by", None),
    ("P7", "Your role / title", "Role / title", None),
    ("P8", "Your email address (the report will be sent here)", "Email address (to send yourself the report)", None),
    ("P9", "Is the organisation licensed by the Central Bank of Bahrain (CBB)?", "Is the organisation licensed by the Central Bank of Bahrain (CBB)?", YN),
    ("P10", "Do AI systems process personal data of individuals in Bahrain?", "Do AI systems process personal data of individuals in Bahrain?", YN),
    ("P11", "Are AI-enabled products / services offered in the EU, or AI outputs used in the EU?", "Are AI-enabled products / services offered in the EU, or AI outputs used in the EU?", YN),
    ("P12", "Does the organisation operate in KSA, UAE or other GCC markets?", "Does the organisation operate in KSA, UAE or other GCC markets?", YN),
    ("P13", "Is the organisation a government entity or public-sector body?", "Is the organisation a government entity or public-sector body?", YN),
    ("P14", "Does the organisation develop AI (provider) or only use it (deployer)?", "Does the organisation develop AI (provider) or only use it (deployer)?", ROLES),
]
